<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>9f754256-c7b5-4d68-9500-4327756d2e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Login')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mb-header__main__link.js-menu-link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d02582cc-f690-4c5f-9140-a8f7eda60dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-header__main__link js-menu-link active</value>
      <webElementGuid>f66b1d93-2961-42f9-a9a6-c95ce6ec036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>44a20c2b-f582-422b-af1f-b6631b541289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a46dd68c-6bc0-49e6-80fa-0d6bf9346c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mb-home homeIndex&quot;]/header[@class=&quot;mb-header&quot;]/section[@class=&quot;mb-header__main&quot;]/div[@class=&quot;mb-container mb-header__main__section&quot;]/div[@class=&quot;mb-header__main__login js-menu-container active&quot;]/a[@class=&quot;mb-header__main__link js-menu-link active&quot;]</value>
      <webElementGuid>8e5401cb-a8dd-48e0-b719-c506c1fd75a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a1606e4-5ed3-4bf3-8efb-1a63c12deb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-header__main__link js-menu-link active</value>
      <webElementGuid>6f7747f5-b7b0-46fb-b6d1-868924125c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>0cdfdecb-8224-4c23-bd53-3befb9be85c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>b5d7f931-8308-421c-95a2-b1efd549a575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mb-home homeIndex&quot;]/header[@class=&quot;mb-header&quot;]/section[@class=&quot;mb-header__main&quot;]/div[@class=&quot;mb-container mb-header__main__section&quot;]/div[@class=&quot;mb-header__main__login js-menu-container active&quot;]/a[@class=&quot;mb-header__main__link js-menu-link active&quot;]</value>
      <webElementGuid>a1f7c3d0-b415-4789-b62d-4919694082b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>0d779629-27f8-49fa-8521-31b37402b42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[1]/following::a[1]</value>
      <webElementGuid>48b0ffb4-08c6-40f0-9f48-f34c3b770b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[1]/following::a[2]</value>
      <webElementGuid>5b720d02-2162-4c3a-b02f-6ce9ca7bbac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Activity'])[1]/preceding::a[1]</value>
      <webElementGuid>e4702cdf-d2c6-47c5-ba5f-8cec938a0afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacted Properties'])[1]/preceding::a[1]</value>
      <webElementGuid>f0f61ac0-91da-4824-b5eb-a5b7ce5e7a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>c89ccd18-5788-4dd0-94e0-25c73c957c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>7122776d-09aa-4657-b640-3383d2dd9173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>b55e19eb-6753-4ad5-8610-513e21c4cc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>b0c09ab3-0ce1-4762-9d92-a332336aefed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
