<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bangalore</name>
   <tag></tag>
   <elementGuidId>dc929ab7-70fc-4abe-8b28-544f96cbf439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__tag-t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8074082e-18be-4684-b5e8-4e3ea5d02307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tag-t</value>
      <webElementGuid>7642364a-4f93-45bb-bd7a-f7aafb5d8201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3327</value>
      <webElementGuid>d081ed22-5f60-4c96-924e-af7c2524dbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bangalore</value>
      <webElementGuid>5b386b2a-1b7c-4eb3-80b7-5d621a9f90f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)/div[@class=&quot;mb-search__tag&quot;]/div[@class=&quot;mb-search__tag-t&quot;]</value>
      <webElementGuid>4aec8c2b-86fa-447e-bd08-ace61395c466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5ad84ba-4791-461b-b295-f16d87f0988e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__location__tag-wrap forFlexView mb-search__compact-view</value>
      <webElementGuid>95fbd651-0204-417e-a617-1bdbe30d68bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword_autoSuggestSelectedDiv</value>
      <webElementGuid>471ec91b-f0b6-4e52-b86d-071d0c13a920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.stopPropagation(); $('#keyword').focus();fireSearchBoxClickedGTM();</value>
      <webElementGuid>8b3fad65-2202-450a-9173-eeb11451e2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Bangalore</value>
      <webElementGuid>f3b242db-e8d4-43e4-a53b-4fdfe6f2bb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)</value>
      <webElementGuid>c72fb72f-2560-4456-9be0-53a70a78209c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div</value>
      <webElementGuid>a7386821-65ef-4384-bc80-6fc7e0c69f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/following::div[5]</value>
      <webElementGuid>5dfc4db5-3475-46fc-a916-1b37cf4df403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/following::div[5]</value>
      <webElementGuid>84385110-86a3-4b97-b345-84272ad09cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can enter'])[1]/preceding::div[3]</value>
      <webElementGuid>eead4a03-ee3a-46dd-9fce-a9e48db0b4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>010252aa-cf15-446b-871d-8b587a32a473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bangalore' or . = 'Bangalore')]</value>
      <webElementGuid>d18eabdd-e3b0-4b12-b0a0-9c775488a258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']</value>
      <webElementGuid>28405ba0-2732-4782-b014-2f9dea9816b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[3]/div/div</value>
      <webElementGuid>50553491-85de-415c-9c95-2064eb682391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/following::div[3]</value>
      <webElementGuid>0e01741e-2759-43d2-889b-9f0db55b22b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/following::div[3]</value>
      <webElementGuid>1fc22675-b897-4bd3-a681-9c2bff6cce39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div</value>
      <webElementGuid>9568e2af-d229-47c1-b705-c8fd904e444a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'keyword_autoSuggestSelectedDiv' and (text() = '

Bangalore' or . = '

Bangalore')]</value>
      <webElementGuid>94188465-1d55-4525-9eab-3b1cf951744e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
