<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pick your perfect piece of plot</name>
   <tag></tag>
   <elementGuidId>fb6e4d8d-5609-4cfb-ad1f-719a756c02e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home_page_msg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home_page_msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b9efc1a-9d58-4bf3-a877-7d3fa0111aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__heading</value>
      <webElementGuid>dd774bc8-39e7-4a03-b071-f627a4f65d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_page_msg</value>
      <webElementGuid>3484f0de-0ba2-4381-a243-276b5990e0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Pick your perfect piece of plot
</value>
      <webElementGuid>14d7f265-3ab1-4abe-8965-12bfb6d62856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_page_msg&quot;)</value>
      <webElementGuid>4fd75f66-67f1-4e0c-af84-aa9957d5059c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home_page_msg']</value>
      <webElementGuid>39584b91-e2ca-4958-a1bc-23a318eb809b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='plotIndex']/section/div/div/div</value>
      <webElementGuid>66bf2fc7-d231-4460-802f-573fa99f8733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay your Rent'])[1]/following::div[3]</value>
      <webElementGuid>27074490-1370-4d6b-ada9-9b0bf02dc6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Enquiry'])[2]/following::div[4]</value>
      <webElementGuid>81327a58-7ef0-437c-9b2c-5e31f089a7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/preceding::div[1]</value>
      <webElementGuid>6a523145-12b4-4844-9e68-367ba8b6b227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pick your perfect piece of']/parent::*</value>
      <webElementGuid>45e2ec1f-8913-47c9-b293-2bd5518f9b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/section/div/div/div</value>
      <webElementGuid>66cbee60-4bf7-4fcb-9f27-deef857ab749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home_page_msg' and (text() = '
Pick your perfect piece of plot
' or . = '
Pick your perfect piece of plot
')]</value>
      <webElementGuid>353e0382-1935-43a5-beb0-6b47ff7cf355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
