<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Field Agent will be visiting you so_c9017e</name>
   <tag></tag>
   <elementGuidId>dce4d722-59f9-4193-b1ed-c68657cba0e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b15ad0aa-051c-4f27-9b43-d693f384ba81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-close</value>
      <webElementGuid>d7a5054d-5ad6-4538-b76d-6faa71e29b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closePopup('pgpckgPopup')</value>
      <webElementGuid>d540e4dc-2ad4-44dd-8966-e0ba9c5037b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgpckgPopup&quot;)/div[@class=&quot;m-popup__table&quot;]/div[@class=&quot;m-popup__table-cell&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;m-popup__content&quot;]/div[@class=&quot;m-close&quot;]</value>
      <webElementGuid>62ba80a3-f86c-4363-8551-f2ac4c177fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd252075-9c8f-4366-8029-a057c6fd4f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-close</value>
      <webElementGuid>bcad078a-3f4e-4883-b542-22530e7b00d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closePopup('pgpckgPopup')</value>
      <webElementGuid>a8d151a8-6a41-4c05-a545-782d93895ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgpckgPopup&quot;)/div[@class=&quot;m-popup__table&quot;]/div[@class=&quot;m-popup__table-cell&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;m-popup__content&quot;]/div[@class=&quot;m-close&quot;]</value>
      <webElementGuid>4049fa35-d8fa-4310-a151-7b57fc2b4775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      <webElementGuid>4918c855-b864-4743-b35a-04aaf5330902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgpckgPopup']/div/div/div/div/div</value>
      <webElementGuid>b3037a87-6a10-4357-8605-49c1378a4586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>edaa90f8-e26b-4589-afb1-52b2e034e122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
