<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Single</name>
   <tag></tag>
   <elementGuidId>6b584510-d8c4-4f90-8918-77b113fae4d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slide_pg-roomtype']/div/div[3]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mobile-form__checkbox-thumb__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c666b758-ce62-457c-8045-85b18a5565a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-form__checkbox-thumb__label</value>
      <webElementGuid>f83f95d1-d13d-4236-a172-0278ce8cad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single</value>
      <webElementGuid>0c31ab3b-3166-4335-9507-0abc9ad8fcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide_pg-roomtype&quot;)/div[@class=&quot;mb-pg__screen__left&quot;]/div[3]/div[1]/div[@class=&quot;mobile-form__checkbox-thumb js-checkbox&quot;]/div[@class=&quot;mobile-form__checkbox-thumb__label&quot;]</value>
      <webElementGuid>2066ab8a-6478-43f0-8234-4063cd2ca386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4ac8c80-dc6a-49d6-85e5-c18ba7d17218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-form__checkbox-thumb__label</value>
      <webElementGuid>8b17ef30-79ed-42d3-a4a5-ccde5a0de689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single</value>
      <webElementGuid>7c85d7a0-53a2-476d-b1c0-b0d9c3af56be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide_pg-roomtype&quot;)/div[@class=&quot;mb-pg__screen__left&quot;]/div[3]/div[1]/div[@class=&quot;mobile-form__checkbox-thumb js-checkbox&quot;]/div[@class=&quot;mobile-form__checkbox-thumb__label&quot;]</value>
      <webElementGuid>682ed413-4f19-4297-a7d9-5d8079f2645d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-roomtype']/div/div[3]/div/div/div[2]</value>
      <webElementGuid>bb779fed-dc81-43ce-a73e-d361e7f134aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all the available room categories in your PG'])[1]/following::div[5]</value>
      <webElementGuid>78443c1f-3b0c-406a-bf3d-f3f44e7198f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room Categories in your PG'])[1]/following::div[6]</value>
      <webElementGuid>e5e8c0f9-d6b6-4b6f-aa76-06e089cd2ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double'])[1]/preceding::div[2]</value>
      <webElementGuid>e0ada887-7380-408f-beb8-c1f0ea161e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triple'])[1]/preceding::div[5]</value>
      <webElementGuid>12554ddc-5358-47e6-b77d-4abf09ed35d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single']/parent::*</value>
      <webElementGuid>2b738458-5a1d-4448-b6fb-796af2b7d076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/div/div/div[2]</value>
      <webElementGuid>84a86822-f24c-42f9-bd9d-8f764b366fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Single' or . = 'Single')]</value>
      <webElementGuid>a5803d33-7d3b-4e69-9a6e-dafdee9c83a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
