<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Move into Test_PG, a professionally man_ff5454</name>
   <tag></tag>
   <elementGuidId>7ebed091-e066-464b-8a30-c09ba8276c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pgDescSample1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pgDescSample1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2821278-68ee-44b3-9ed6-be983cf6ef33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__card__more-content</value>
      <webElementGuid>27e04e1e-1cd1-4e42-b912-dc3dd344ed0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgDescSample1</value>
      <webElementGuid>47032199-9882-491e-95f2-763d78937bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Move into Test_PG, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.</value>
      <webElementGuid>86c46c1f-0969-4520-b2f8-d14952571571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgDescSample1&quot;)</value>
      <webElementGuid>39cb739e-03ca-4dfd-8b2b-56dba2c53e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pgDescSample1']</value>
      <webElementGuid>c5f2f656-c6db-4b80-ad67-58c56ab0478f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-moredetails']/div/div[5]/div[3]/div[2]</value>
      <webElementGuid>c49c4760-c5ae-4a18-b93c-c07bade514e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample 1'])[1]/following::div[1]</value>
      <webElementGuid>06e3abcf-5d34-445f-894f-c2f6d1f885b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample Description'])[1]/following::div[3]</value>
      <webElementGuid>4014a658-5c4e-4b1b-8dcd-a5c3dfe1843d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit &amp; Use'])[1]/preceding::div[1]</value>
      <webElementGuid>82abf998-8a93-459a-a7c6-fa7ac0b226f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample 2'])[1]/preceding::div[2]</value>
      <webElementGuid>ac383fc8-200a-4d67-801d-d58084ed0b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Move into Test_PG, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.']/parent::*</value>
      <webElementGuid>630713c2-f011-46f8-b07a-c4b837000eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]</value>
      <webElementGuid>b830b701-9af2-4b40-9634-e05fb8b4f427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pgDescSample1' and (text() = 'Move into Test_PG, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.' or . = 'Move into Test_PG, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.')]</value>
      <webElementGuid>4748b48b-58cc-43bc-a73a-5be6c981db1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
