<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__depositPerBed_16011</name>
   <tag></tag>
   <elementGuidId>9ec19bb7-65a6-4282-bab8-c3b53aad294b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='depositPerBed_16011']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#depositPerBed_16011</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfe40656-e971-40c0-8e25-3badea41d304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>406ebfa4-7eac-4541-aa13-79062e809e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>56d8a57f-0a31-4ea4-aa2f-33ec3585a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>depositPerBed_16011</value>
      <webElementGuid>09c2b270-bb3d-4720-b427-5ce00055fac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depositPerBed_16011</value>
      <webElementGuid>4250ec3a-e12f-4b94-a839-71e99ff8aabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>9ab7ab7b-d045-46af-a704-09d2df75e748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>1aa3173d-f438-4eef-b255-f3d5746a38f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depositPerBed_16011&quot;)</value>
      <webElementGuid>e4dff03f-72eb-42e5-81ca-352a2e9e1bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>569a5910-9ab8-442f-bda9-26a2b8fb6e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>d87fc096-ab33-4f87-8ca1-297045389ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d965e6d3-492e-4f00-9e8c-97de6e4b7082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>depositPerBed_16011</value>
      <webElementGuid>637c542e-55a7-4b40-b7b0-1b6640a95b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depositPerBed_16011</value>
      <webElementGuid>c62a878d-942f-45ad-820a-af949e53b471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>3acf43d7-afbc-4404-915a-db1447a74c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>7921da7e-1f4b-422f-94fd-def1cbbb82f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depositPerBed_16011&quot;)</value>
      <webElementGuid>7cf87bb5-02dd-4f5b-b63d-f1bfc66a1596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='depositPerBed_16011']</value>
      <webElementGuid>782191ad-dfa9-490e-9bcb-4cd3042a82a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roomDetail_16011']/div[3]/div/div[3]/input</value>
      <webElementGuid>74bdb0bd-552b-4e9b-881a-b9192e8ead94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/input</value>
      <webElementGuid>fffd2c79-98bb-46dd-bc01-5d3efef5c9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'depositPerBed_16011' and @id = 'depositPerBed_16011']</value>
      <webElementGuid>c10462b3-db5c-4863-b991-a6e39569fca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
