<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make sure you enter the correct addre_b9e526</name>
   <tag></tag>
   <elementGuidId>a0eb5e07-d9bc-42b0-b540-5d5b09b920ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedLocality']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedLocality</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3700e81e-f13d-40c5-b595-48f71d8f20e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__slide__location__input js-autosuggest</value>
      <webElementGuid>0d3f6fe1-1bb1-4303-ad67-74f45777b6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>07b6836c-d8fc-4255-a934-f6be8b1476ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Locality</value>
      <webElementGuid>3de41170-5be0-49ac-9f1d-d8d49c02e438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>57f5cfff-1438-4840-acd2-79308dd6ab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>14f90672-1fb2-4329-85f5-0aa93356187d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLocality&quot;)</value>
      <webElementGuid>f77d8fc7-a0dd-41c2-a71d-1b673ccbbca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aede41f-c066-4ff9-8a48-b650dcae3a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__slide__location__input js-autosuggest</value>
      <webElementGuid>51b96ae1-aad7-494a-bf4c-a0f6957f9fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33a83f19-c97c-4711-910b-e7fbdaf13874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Locality</value>
      <webElementGuid>d7e95050-e1e5-4eb3-b1be-2c708ce2aeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>a180c735-c9c1-4ba5-85f3-33be047d5943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>73b6e9c1-8f44-4173-886c-d97e952f8a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLocality&quot;)</value>
      <webElementGuid>131d39fc-403d-4d42-a04f-6ac03ba13e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedLocality']</value>
      <webElementGuid>c899605f-9f28-49aa-aff9-4ba279162183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-location']/div/div[3]/input</value>
      <webElementGuid>08cade86-9251-4fd9-af69-1d224662ff3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d7ae4e25-2bb1-48c5-8a0b-f7f9d83688e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Locality' and @id = 'selectedLocality' and @name = 'selectedLocality']</value>
      <webElementGuid>743af727-34c8-4411-9e7a-f75b57388667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
