<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Long Island, Andaman  Nicobar</name>
   <tag></tag>
   <elementGuidId>6c35c5e0-0e4a-4706-af8d-0986053a93fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='locality_options']/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.js-dropdown-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>57a3187e-a750-4658-a558-2dc297ce4393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-dropdown-element</value>
      <webElementGuid>175dab5a-412c-4464-a6f8-c1199e91f282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-city</name>
      <type>Main</type>
      <value>7058</value>
      <webElementGuid>5cdeecee-bf5c-4478-9532-c986215cbfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>ac3778d3-8acd-4706-a65b-cb934cff844d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locality</name>
      <type>Main</type>
      <value>Long Island, Andaman &amp; Nicobar</value>
      <webElementGuid>ddb9428b-ee5a-4687-a8fa-e97f03eaa92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-latitude</name>
      <type>Main</type>
      <value>12.4051021</value>
      <webElementGuid>88a139b2-4bda-4b0e-bd95-9f4dab50d79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-longitude</name>
      <type>Main</type>
      <value>92.9325785</value>
      <webElementGuid>2d46bfcc-649d-4dfa-b235-1e20ae85e8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lmtrfnum</name>
      <type>Main</type>
      <value>74979</value>
      <webElementGuid>6e0285f2-086b-45eb-9127-3ffd23827fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Long Island, Andaman &amp; Nicobar
							</value>
      <webElementGuid>a87ce7a3-3404-4b22-8c64-564b73488488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locality_options&quot;)/li[@class=&quot;js-dropdown-element&quot;]</value>
      <webElementGuid>2ad5c374-d78b-44d4-b7ea-502d04b697e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='locality_options']/li</value>
      <webElementGuid>c68f96a1-5c74-4271-af14-6a5ccda78b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure you enter the correct address for a smooth verification.'])[1]/following::li[1]</value>
      <webElementGuid>ff3803a6-ecc1-4d1c-84bc-c0aef83a90f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where is your PG Located?'])[1]/following::li[1]</value>
      <webElementGuid>609dd3c4-2f6e-44a4-b701-121690a4d078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Long Island,']/parent::*</value>
      <webElementGuid>fa1a223e-b796-48f0-b37c-08c55ceebf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>219b276f-3b57-40f8-b43e-7286bd45e885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
								Long Island, Andaman &amp; Nicobar
							' or . = '
								Long Island, Andaman &amp; Nicobar
							')]</value>
      <webElementGuid>52e6ec54-06cf-46d0-8919-4546bf942966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
