<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Andaman</name>
   <tag></tag>
   <elementGuidId>586e94b6-87a1-4f2f-8a9c-71f7e62d7d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='locality_options']/li/mark</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>823e474e-b343-4e3f-9cde-c0f9a42911b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andaman</value>
      <webElementGuid>b29a45a8-acab-42aa-96b0-49b0dcb3540b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locality_options&quot;)/li[@class=&quot;js-dropdown-element&quot;]/mark[1]</value>
      <webElementGuid>e4c53bff-6e8e-40fb-a2d9-c72580826487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='locality_options']/li/mark</value>
      <webElementGuid>ccaabf96-d420-45fd-a49f-3da7b855664a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure you enter the correct address for a smooth verification.'])[1]/following::mark[1]</value>
      <webElementGuid>622a501d-2fa9-43bc-98b3-d8ebd4b879d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andaman'])[2]/preceding::mark[1]</value>
      <webElementGuid>ce61c79f-7948-45c2-bdff-7a552319bf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Andaman']/parent::*</value>
      <webElementGuid>a36f361d-072f-4f05-8198-860e277bdf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mark</value>
      <webElementGuid>e00230f7-71a9-4332-bd0d-2d8dccbe5bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'Andaman' or . = 'Andaman')]</value>
      <webElementGuid>a76418cf-a6f6-440f-9946-cf319e76e922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
