<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tell us more about your PG_pgdescription</name>
   <tag></tag>
   <elementGuidId>89d5de16-a9ce-4192-985f-6a9dfd317a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pgdescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pgdescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>101e04e4-f8d9-4e23-961c-7afbe8fc66cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input mb-form__textarea</value>
      <webElementGuid>485ae9cc-45e5-4dc1-b120-572ccd66dbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>mbPgUi.autoGrow(this)</value>
      <webElementGuid>764fe12f-9b54-4a94-a9e0-fe48080e7396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgdescription</value>
      <webElementGuid>6f1fc659-cefe-46ed-873c-7a322d716419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgdescription</value>
      <webElementGuid>3f0993dd-87c5-4959-bfda-5f616822f676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgdescription&quot;)</value>
      <webElementGuid>da5bba6e-8a0a-4bba-9d89-60a6db99a9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pgdescription']</value>
      <webElementGuid>e6e8af99-bfa9-4bd9-8154-8d38892b2e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-moredetails']/div/div[3]/div/textarea</value>
      <webElementGuid>f22dbf16-2fd3-4287-9bde-ea3df9f67361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c1eb19e1-22ad-4459-94f6-93d4b01235da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pgdescription' and @name = 'pgdescription']</value>
      <webElementGuid>0fc15558-98bd-421a-996e-4a18558238db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
