<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>b4c21ac8-3002-4de5-b8fc-a64c832c1c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mb-login__drop-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;window.open('https://accounts.magicbricks.com/userauth/login', '_blank');fireLoginGTM(event,'Login','Login CTA clicked','');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>816ceb92-7c93-4d8f-8c0c-6200be718630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>3897e8d0-dbef-47ff-83b9-1f2b07252c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-login__drop-cta</value>
      <webElementGuid>6371fa2d-f52e-47e6-b5be-534bbb25a6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('https://accounts.magicbricks.com/userauth/login', '_blank');fireLoginGTM(event,'Login','Login CTA clicked','');</value>
      <webElementGuid>7e8a3309-4882-4d6b-86dd-40cc327ccebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>03a81b15-243a-4c4b-9de8-51212dfc7721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mb-home homeIndex&quot;]/header[@class=&quot;mb-header&quot;]/section[@class=&quot;mb-header__main&quot;]/div[@class=&quot;mb-container mb-header__main__section&quot;]/div[@class=&quot;mb-header__main__login js-menu-container active&quot;]/div[@class=&quot;mb-header__main__dropdown mb-login js-menu-drop active swiper-created&quot;]/div[@class=&quot;mb-login__box signup-box&quot;]/a[@class=&quot;mb-login__drop-cta&quot;]</value>
      <webElementGuid>9e344847-c48f-4456-846c-884ff57c6f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;window.open('https://accounts.magicbricks.com/userauth/login', '_blank');fireLoginGTM(event,'Login','Login CTA clicked','');&quot;]</value>
      <webElementGuid>b733c5ed-c2af-402d-a9c4-c7fb4cde3534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>3fec72dc-7da4-4b2d-8032-446c91f75437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::a[1]</value>
      <webElementGuid>bb2d4b0d-12e2-4699-a73d-dbf9058613a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommendations'])[1]/following::a[2]</value>
      <webElementGuid>778fd75d-9df0-4874-9200-7be2933b991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::a[1]</value>
      <webElementGuid>f3d0e8ba-a738-45b9-b189-40ac23e03292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[9]</value>
      <webElementGuid>b0e99d88-abfc-4014-9fe2-c9c101cd3724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/a</value>
      <webElementGuid>d0926c75-55c7-447f-978f-04f8586ad2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>1d57d411-ec55-4bf1-87e4-560bb1f616a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
