<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>d80ae601-7344-437e-919f-bb8b156fc975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='commercialIndex']/header/section/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mb-header__main__link.js-menu-link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6abc8d0-fd90-4177-a06d-3c1619579752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-header__main__link js-menu-link active</value>
      <webElementGuid>6e676a0b-a0a1-4326-8700-b65faedf6861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b28d7c4f-6a73-4ed9-8317-d53582b8802b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>2d3af7e1-4fdd-4d7a-8c43-97f29d2e6b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commercialIndex&quot;)/header[@class=&quot;mb-header&quot;]/section[@class=&quot;mb-header__main&quot;]/div[@class=&quot;mb-container mb-header__main__section&quot;]/div[@class=&quot;mb-header__main__login js-menu-container active&quot;]/a[@class=&quot;mb-header__main__link js-menu-link active&quot;]</value>
      <webElementGuid>7e581a4c-2057-4ac4-99cc-33e98690c0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d603c1e8-ec21-4855-98ec-0a271e9486bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-header__main__link js-menu-link active</value>
      <webElementGuid>3d87e1e3-1a9a-44ae-b734-fee9019a2086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>2999ba8a-39c7-4bf7-8798-2e0423891ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c899990f-58ba-46b0-b4ac-f63466af330b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commercialIndex&quot;)/header[@class=&quot;mb-header&quot;]/section[@class=&quot;mb-header__main&quot;]/div[@class=&quot;mb-container mb-header__main__section&quot;]/div[@class=&quot;mb-header__main__login js-menu-container active&quot;]/a[@class=&quot;mb-header__main__link js-menu-link active&quot;]</value>
      <webElementGuid>8efeda97-c75b-4fc0-a030-7300245e95e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='commercialIndex']/header/section/div/div[4]/a</value>
      <webElementGuid>798936d8-4789-46fe-9ccf-f5baa5674721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>addf08dc-2a56-4a0e-afe3-f8b7b23d3a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Now'])[1]/following::a[1]</value>
      <webElementGuid>c1097124-4126-4693-9885-9a1545adcd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exclusive partner discounts'])[1]/following::a[2]</value>
      <webElementGuid>363272f9-056f-4479-8ff8-90c2fb2a129b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Activity'])[1]/preceding::a[1]</value>
      <webElementGuid>0ad40368-3aee-4be8-b328-e417e5471d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacted Properties'])[1]/preceding::a[1]</value>
      <webElementGuid>8e374725-e725-463e-84d6-49a83dd85fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>e1b0e1fd-ffec-4aa0-8824-faa7628c5134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>f9afc0cf-11c0-4b5e-9e7b-2a94179ed065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>3082b877-f938-40b9-b0a5-e429d8d20fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>f783fc39-68fe-404f-9002-725362a2828e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
