<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>24627ff2-2ec7-431b-af95-8bafba8a850d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='redirectPgUrl();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn_pg-continue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b2ba95a-b085-4b4b-8fc5-1b21b3066a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>38d37531-3b4a-48f2-a747-b121df4d42ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectPgUrl();</value>
      <webElementGuid>182514e0-9022-4ea8-8433-6fc91574b40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_pg-continue</value>
      <webElementGuid>cfebc8cc-d478-4452-98ab-dde71f7bcbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>72b3d734-68e1-4499-b84a-83529549b0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgSpecificRedirectDiv&quot;)/div[@class=&quot;form_element_group&quot;]/a[@class=&quot;btn_pg-continue&quot;]</value>
      <webElementGuid>6c38713d-4190-4356-93a7-858d3468a5de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='redirectPgUrl();']</value>
      <webElementGuid>e734fe16-00c1-4c68-9917-6075b16814d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgSpecificRedirectDiv']/div[2]/a</value>
      <webElementGuid>c7b0e6ee-6c68-4331-8e5e-a921684634f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Continue')])[5]</value>
      <webElementGuid>1168e5c8-c309-45be-98c9-5ec26a8c9224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Get started with our new listing form - it', &quot;'&quot;, 's super quick and simple.')])[1]/following::a[1]</value>
      <webElementGuid>a7a848e8-1fa3-44ea-9f6e-514d27cb0a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now post your Property in just a few minutes!'])[1]/preceding::a[1]</value>
      <webElementGuid>be78712e-5f8f-4ef3-b892-ee955186fcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Get started with our new listing form - it', &quot;'&quot;, 's super quick and simple.')])[2]/preceding::a[1]</value>
      <webElementGuid>389eefea-dab3-4c71-a4ed-ac8b78e3ff51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>00b4aab5-5db5-4c38-8728-e2087c289114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c3762ba8-9d28-409d-a4c5-e57b6d3cc5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>ad11a12d-4f61-430a-81c5-135b2a5f07b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
