<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rent Lease_propertyFor</name>
   <tag></tag>
   <elementGuidId>9db66b99-bd65-4b84-91b6-4bc341ba65d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyForP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propertyForP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a68fb72-e73c-48ec-97fd-4d6f8758f53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyForP</value>
      <webElementGuid>d0b45a36-594f-481a-b8d4-588405fa6afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyFor</value>
      <webElementGuid>143a4312-207d-44a4-9817-980c8fce07fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setflatmat(),customRadioButtonNew(this, 'propertyFor'), showHideDropDown(); firestep2ga('P');</value>
      <webElementGuid>996f59e8-d8a9-4c87-aa6f-4bc41331d3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>98d09474-92ad-4434-87fd-90d1ace36657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>5601fa99-d84b-45c5-8c2a-a87424b5b933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForP&quot;)</value>
      <webElementGuid>85c70e85-5ccb-4d12-8724-f754afbbfd09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyForP']</value>
      <webElementGuid>16850c32-79bd-4b3e-9b5b-a3803e9b7680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postProperty']/div[9]/div/div[2]/div[2]/div/ul/li[3]/span/input</value>
      <webElementGuid>115baebf-7daa-4346-8809-147b88ec6b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/input</value>
      <webElementGuid>0db9c23e-aee2-48e6-9da1-ad10530089e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyForP' and @name = 'propertyFor' and @type = 'radio']</value>
      <webElementGuid>e8aaadd3-9569-4fff-adcc-d7df78ffca4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
