<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rent Lease_propertyFor</name>
   <tag></tag>
   <elementGuidId>1dcdbda1-b93f-4a8b-bef2-27543954655c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyForP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propertyForP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>050436e1-bf19-4e8c-a7e8-8904f8590a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyForP</value>
      <webElementGuid>a539f17b-55d0-490a-aac7-77ee0edb881d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyFor</value>
      <webElementGuid>ef2b21c8-a7be-479e-918d-1ea212d34a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setflatmat(),customRadioButtonNew(this, 'propertyFor'), showHideDropDown(); firestep2ga('P');</value>
      <webElementGuid>e8cef168-9a3f-4d4c-9ea5-5705e6eada07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a440be85-e385-48b0-a7c0-c95ea31262f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>d16107e0-6ed3-4334-ad1c-b68d3157403a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForP&quot;)</value>
      <webElementGuid>23e33f3f-5185-4e63-a9d3-5e374407aec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49d843f9-72d7-4464-b2c5-d120e2e8f3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyForP</value>
      <webElementGuid>edbb7cf0-c1cd-4f5d-a710-38408301ba35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyFor</value>
      <webElementGuid>9bdde081-305d-4da3-b1ed-44636959ee0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setflatmat(),customRadioButtonNew(this, 'propertyFor'), showHideDropDown(); firestep2ga('P');</value>
      <webElementGuid>dc8ab927-dc3a-430e-9e29-ac13f703a257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65748c8b-c840-4e5f-bcb3-7915b4ae3713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>7605c701-956e-4eb2-8dde-f489c3134783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForP&quot;)</value>
      <webElementGuid>cf98c09a-249f-4b3d-889c-b329ce39cc73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyForP']</value>
      <webElementGuid>a1e827a2-3324-424a-9b91-4137b1d84c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postProperty']/div[9]/div/div[2]/div[2]/div/ul/li[3]/span/input</value>
      <webElementGuid>83c76935-ed25-4b07-9b46-ab6e2f82a4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/input</value>
      <webElementGuid>db401f28-304c-4214-a0a8-c2349ba01de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyForP' and @name = 'propertyFor' and @type = 'radio']</value>
      <webElementGuid>3826a14d-766f-4bce-b9fe-92cd86488a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
