<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Plot</name>
   <tag></tag>
   <elementGuidId>9038d16e-bc45-450f-b562-91f04eba611b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabPLOT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabPLOT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>513009ee-685f-4ab3-aca4-55d50e4c8f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>01f8f8f8-a812-4106-a7b2-393aedeb9317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabPLOT</value>
      <webElementGuid>011f416a-2c79-4b7d-90f3-48bc14e92922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Mumbai/Plots-Land-Mumbai</value>
      <webElementGuid>e5144d12-b1e1-4c3a-8cdc-e7d559d1685c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'Plot');openPgTabUrl(this);</value>
      <webElementGuid>8aa19e96-0f7c-4072-a53e-312c5db98a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plot</value>
      <webElementGuid>c47d4088-3904-471a-913b-338583acf43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPLOT&quot;)</value>
      <webElementGuid>7e52d61d-c38a-4516-b29a-5c90e7569036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabPLOT']</value>
      <webElementGuid>7fe0f655-63be-4ae0-9cfa-f3393cd41641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div[4]</value>
      <webElementGuid>11998d80-3ddf-4ca3-9f2d-5d4490278f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[1]/following::div[1]</value>
      <webElementGuid>88dc68db-7eed-4b05-b07b-5c7db743a14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent'])[2]/following::div[2]</value>
      <webElementGuid>b17f76c3-081d-4493-b984-6d9ac689edbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/preceding::div[1]</value>
      <webElementGuid>761c8a10-04dd-4bee-80dd-04b3a2f823b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/preceding::div[2]</value>
      <webElementGuid>2683d6ff-b6bb-434f-bfaa-4f48d1c99e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Plot']/parent::*</value>
      <webElementGuid>ff02ca2e-9a77-47a1-b63b-b9fd5fba6da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div[4]</value>
      <webElementGuid>66c08f96-a562-4a10-b137-fa260e82d3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabPLOT' and (text() = 'Plot' or . = 'Plot')]</value>
      <webElementGuid>5a7d213e-189d-4db2-a955-2eca9d096220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
