<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PG</name>
   <tag></tag>
   <elementGuidId>cb25bd04-520b-4c8e-b7d5-eff9b0b28df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabPG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabPG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c2b1303-1143-42db-baea-2b8539ebbe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>1897255b-8e62-4139-845e-7587e6fc845d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabPG</value>
      <webElementGuid>1c62cd2a-b0ce-48fb-b2d0-3508603f0cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/pg-hostels-Bangalore</value>
      <webElementGuid>fa0267e3-b0d2-48c2-a396-d29ac32f74db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'PG');openPgTabUrl(this);</value>
      <webElementGuid>dbe270b8-6cab-4c5a-bde3-af107afb2d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PG</value>
      <webElementGuid>321a62fc-73a2-4b13-9da8-a8c1a1548808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPG&quot;)</value>
      <webElementGuid>f6881b58-8814-4fe2-8166-767eb4b0f0ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabPG']</value>
      <webElementGuid>807a58f2-4497-461a-89f3-8d97798a5fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div[3]</value>
      <webElementGuid>69d638a1-0704-4997-b49f-8f3b8c11ca5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent'])[2]/following::div[1]</value>
      <webElementGuid>b81d7ba5-0b37-4292-bd7b-56a0b50c2603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/following::div[2]</value>
      <webElementGuid>73d2b2f7-af85-4c81-97c2-fba4d95c5253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plot'])[1]/preceding::div[1]</value>
      <webElementGuid>a21a5800-d7c1-4d4e-8a2c-0c472185a123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[3]/preceding::div[2]</value>
      <webElementGuid>4bf251c8-8cfb-4852-bccc-ee34323cb470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div[3]</value>
      <webElementGuid>a618930a-5d58-48ca-a7b9-cf6b6cf63b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabPG' and (text() = 'PG' or . = 'PG')]</value>
      <webElementGuid>3d730414-d9ea-4f8f-92c9-ff1429a95304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
