<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>01db8fdf-5b70-4a07-9daa-f492ac50197e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='commercialIndex']/header/section/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mb-header__main__link.js-menu-link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dec9ad51-a131-49dd-8d85-d2a36323344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-header__main__link js-menu-link active</value>
      <webElementGuid>25527328-b6f6-4aa8-97d3-e886bc16715c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>3852d1c8-cd24-45d8-9961-03e2659fcb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>cefc80cd-4778-40ef-9c5e-b72e3216c43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commercialIndex&quot;)/header[@class=&quot;mb-header&quot;]/section[@class=&quot;mb-header__main&quot;]/div[@class=&quot;mb-container mb-header__main__section&quot;]/div[@class=&quot;mb-header__main__login js-menu-container active&quot;]/a[@class=&quot;mb-header__main__link js-menu-link active&quot;]</value>
      <webElementGuid>1ab36c17-cd5d-472d-8b8e-12a2a4c002cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='commercialIndex']/header/section/div/div[4]/a</value>
      <webElementGuid>bfda4b6d-c676-48fb-acd0-40886e2377e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>e3996066-353b-4fa8-83da-7e34b305f5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Now'])[1]/following::a[1]</value>
      <webElementGuid>54a7e54b-0d79-4676-a05c-b92f2576d093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exclusive partner discounts'])[1]/following::a[2]</value>
      <webElementGuid>fbd9e0dd-23fa-44a5-a6a7-932c86b07e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Activity'])[1]/preceding::a[1]</value>
      <webElementGuid>ee63ae7e-f42c-4544-9bda-b556586fd378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacted Properties'])[1]/preceding::a[1]</value>
      <webElementGuid>c84e11d6-1709-4ecd-ba28-1f0dccbf2a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>1c29f0c8-ef7e-4b62-ab87-f89363d0288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[4]</value>
      <webElementGuid>c1f96902-628f-48a3-a135-db166018450a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>38f519ea-2c0f-41b6-a628-2211e6b8068d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>11a9fc72-ad9a-4ae1-9ea4-d40e0732985f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
