<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Enter Email ID or Mobile No</name>
   <tag></tag>
   <elementGuidId>b1eea8e5-20ae-4bd8-9a72-8f00a831bfc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='firstLoginDiv']/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.m-login__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8f65dc0b-de6f-4cde-bfa2-245f1d03b652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-login__label</value>
      <webElementGuid>95c41857-9d5c-416b-950b-1dbd24fb5646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>emailOrMobile</value>
      <webElementGuid>c1eabf1f-cfb4-4d7e-9b55-e4da5e35e84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Enter Email ID or Mobile No.
			</value>
      <webElementGuid>3565f5dd-68c7-44b5-8296-fedfa928d03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstLoginDiv&quot;)/div[@class=&quot;m-login&quot;]/div[@class=&quot;m-login__fieldset&quot;]/label[@class=&quot;m-login__label&quot;]</value>
      <webElementGuid>94a8c7fa-29c8-44f7-be74-18d288348215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='firstLoginDiv']/div[2]/div/label</value>
      <webElementGuid>b0f7fe05-58d2-41e6-8eca-aed9d6fe8aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::label[1]</value>
      <webElementGuid>423d947a-fd01-49eb-8bd6-0a48bf77dc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add detailed property information &amp; multiple photos per listing'])[1]/following::label[1]</value>
      <webElementGuid>381adde2-a4e5-475b-a87d-6e76e84a4e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::label[1]</value>
      <webElementGuid>53644692-c6db-4a66-b4bc-39639601a122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/preceding::label[1]</value>
      <webElementGuid>520fdc3c-3c01-4193-a0f4-73e4843b45b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Email ID or Mobile No.']/parent::*</value>
      <webElementGuid>b3e99492-6f6a-4e31-a563-ec7a00a40172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>e3d84e20-a279-4aea-870f-c1fcea847b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
				Enter Email ID or Mobile No.
			' or . = '
				Enter Email ID or Mobile No.
			')]</value>
      <webElementGuid>c8a4549e-551f-4a30-8199-4a9c80619864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
