<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Field Agent will be visiting you so_c9017e</name>
   <tag></tag>
   <elementGuidId>ad33444a-195d-4d8c-b93a-0b56c831e79c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b9d93e7-c871-4a03-9b88-da3f6188f6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-close</value>
      <webElementGuid>682a33f1-f0a7-4f90-a911-bcbeae45e8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closePopup('pgpckgPopup')</value>
      <webElementGuid>383d3d72-e7a5-45cf-8c4e-661ba14e5012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgpckgPopup&quot;)/div[@class=&quot;m-popup__table&quot;]/div[@class=&quot;m-popup__table-cell&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;m-popup__content&quot;]/div[@class=&quot;m-close&quot;]</value>
      <webElementGuid>9bf3c89a-0112-416f-bb42-9d9e26fa7aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      <webElementGuid>e1359a3b-e31f-4fb2-b8c9-882290411b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgpckgPopup']/div/div/div/div/div</value>
      <webElementGuid>1b892376-b1ae-442b-a3e8-2fe17285ebfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>cf1f2322-051d-4333-b766-2302c1a578bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
