<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make sure you enter the correct addre_b9e526</name>
   <tag></tag>
   <elementGuidId>a7539e45-8d81-4d68-bc73-48269a763161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedLocality']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedLocality</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>554c1646-8dd7-44ed-93c5-6ecb2621e971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__slide__location__input js-autosuggest</value>
      <webElementGuid>8df2f999-19b3-4713-85ff-ad42618f3433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b929503a-b49e-458b-87bf-5760fc14277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Locality</value>
      <webElementGuid>9438d7df-8cbe-4b3e-afcd-24166c0ca944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>38380f36-b092-40fa-b81d-97aaeb761ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>f8358296-e7c5-4488-84d8-560ef6ab4b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLocality&quot;)</value>
      <webElementGuid>11300f79-29be-4c88-b1c9-2bf75fa7792c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedLocality']</value>
      <webElementGuid>f8f77b08-40d3-4b00-96e6-b2cf8c59c5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-location']/div/div[3]/input</value>
      <webElementGuid>ab2682c3-c7a6-4663-b7c4-afecc9d97847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>432a74c5-1d13-435d-80f6-5dd44c3a2adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Locality' and @id = 'selectedLocality' and @name = 'selectedLocality']</value>
      <webElementGuid>48cf1e8c-3d0f-4204-b710-4e2bf0350a4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
