<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_houseNo</name>
   <tag></tag>
   <elementGuidId>69d8d427-c7ca-463c-aca5-7866429bcc25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='houseNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#houseNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>790cc10c-795a-47e5-bb79-cf9602087cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>2895e882-58fd-4328-92e1-f980d0200869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d710bc8e-f1be-4189-a147-7866c6156fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>houseNo</value>
      <webElementGuid>115be33e-57db-435b-a863-f627d6efb17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>houseNo</value>
      <webElementGuid>82000f9c-2efe-45f9-8461-896f9886e96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;houseNo&quot;)</value>
      <webElementGuid>218437c0-4872-415a-a2d5-fcd416c2d7a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='houseNo']</value>
      <webElementGuid>224f5b1e-260f-4f2b-97d9-56adc6517629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-address']/div/div[4]/div[3]/input</value>
      <webElementGuid>0e799192-b879-44bf-a113-31207a6f89e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>ee1e4cd0-aff5-4606-bf00-642cb3988157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'houseNo' and @name = 'houseNo']</value>
      <webElementGuid>ff3f4a07-4e3b-4297-a6e6-818dabe39d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
