<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Great Nicobar Island, Andaman  Nicobar</name>
   <tag></tag>
   <elementGuidId>918851ed-073b-483c-ac86-cfd1db70ee25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='locality_options']/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.js-dropdown-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a56c8eab-94d6-47eb-8272-01545bd35e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-dropdown-element</value>
      <webElementGuid>70cb54ed-296e-42b3-a909-1354082fc634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-city</name>
      <type>Main</type>
      <value>7058</value>
      <webElementGuid>27fdc2ce-51a8-43f0-adcb-53b9d152d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>65e799f5-4265-4ec9-9d14-a0b9689b4552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locality</name>
      <type>Main</type>
      <value>Great Nicobar Island, Andaman &amp; Nicobar</value>
      <webElementGuid>56630f3e-d708-451b-abdf-3ad5719c4299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-latitude</name>
      <type>Main</type>
      <value>7.0346281</value>
      <webElementGuid>fc40ab0d-aefa-40d2-a8c1-66566ca542a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-longitude</name>
      <type>Main</type>
      <value>93.7841503</value>
      <webElementGuid>9af738e4-72ad-4daa-9979-1dbb391e4c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lmtrfnum</name>
      <type>Main</type>
      <value>74985</value>
      <webElementGuid>b6069327-a3f0-4a08-94d4-ddc09f0f22dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Great Nicobar Island, Andaman &amp; Nicobar
							</value>
      <webElementGuid>07d77f87-a4e5-418d-952c-e2a35281185a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locality_options&quot;)/li[@class=&quot;js-dropdown-element&quot;]</value>
      <webElementGuid>3370660a-19c0-4482-89fc-f36019f3792c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='locality_options']/li</value>
      <webElementGuid>264c46bd-76a1-40a5-9f28-c41b8d5d5670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure you enter the correct address for a smooth verification.'])[1]/following::li[1]</value>
      <webElementGuid>b49a7f00-d4d7-4af8-98db-354ef9a36774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where is your PG Located?'])[1]/following::li[1]</value>
      <webElementGuid>9948e423-5073-49f8-be1b-1bc5ad6fb159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Great']/parent::*</value>
      <webElementGuid>f4d9ab4b-3ae3-4f2f-ac25-d4eb3945d6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>8a3e0215-a678-41a4-bde5-34850565d348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
								Great Nicobar Island, Andaman &amp; Nicobar
							' or . = '
								Great Nicobar Island, Andaman &amp; Nicobar
							')]</value>
      <webElementGuid>ae1b4995-a403-4196-9810-6286be479753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
