<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bangalore</name>
   <tag></tag>
   <elementGuidId>3d592059-aaf8-41b6-8cd3-bf4ef81af33f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keyword_autoSuggestSelectedDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='keyword_autoSuggestSelectedDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f512d22e-c050-44a3-8228-ac0cb441aaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__location__tag-wrap forFlexView mb-search__compact-view</value>
      <webElementGuid>ed36acc9-0b3d-4384-b3a1-5a29d3d3e6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword_autoSuggestSelectedDiv</value>
      <webElementGuid>4f6f703f-fe9e-489f-859c-0d676632145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.stopPropagation(); $('#keyword').focus();fireSearchBoxClickedGTM();</value>
      <webElementGuid>3f14ed4a-d060-4de8-a155-27096542753e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Bangalore</value>
      <webElementGuid>330c6cb0-385b-43fe-846c-b847acdf6fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)</value>
      <webElementGuid>55933bfc-ca4e-40d5-94a1-96b958d2f0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5fb457c-252f-4dc2-9e71-90d3aa2bc9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__location__tag-wrap forFlexView mb-search__compact-view</value>
      <webElementGuid>96223bb3-2a5f-47c8-83c0-4eb20c5412d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword_autoSuggestSelectedDiv</value>
      <webElementGuid>f534c9ae-8c9d-4268-bdb6-15e908c11ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.stopPropagation(); $('#keyword').focus();fireSearchBoxClickedGTM();</value>
      <webElementGuid>46b952bf-f9e5-4fde-9bd3-130f972a1573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Bangalore</value>
      <webElementGuid>1f069317-b04b-42d4-b411-c8f9ad72634b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)</value>
      <webElementGuid>1c019b5d-dc5a-409d-84cc-b923c2926165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f727c14e-4bc4-40f0-88d6-c8aeccb3e49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tag-t</value>
      <webElementGuid>2cb43c5b-9074-419f-86ae-00e54a2318cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3327</value>
      <webElementGuid>5e95c493-1485-4bfe-a539-7a05cc1eb142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bangalore</value>
      <webElementGuid>a9ae4b72-aad0-4d87-b5ac-dd3eeec36029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)/div[@class=&quot;mb-search__tag&quot;]/div[@class=&quot;mb-search__tag-t&quot;]</value>
      <webElementGuid>a37a5886-3cd2-44b5-bbfe-522677ffaef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']</value>
      <webElementGuid>f1f08c08-c977-4ec0-8963-61d416d53ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[3]/div/div</value>
      <webElementGuid>e9b0ccae-cd0b-4779-90cd-eb8ed2f0bfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/following::div[3]</value>
      <webElementGuid>0b8d7247-79de-4009-8601-faf3f00b6323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/following::div[3]</value>
      <webElementGuid>edddd19d-3627-4b98-a216-9e7c1d403430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div</value>
      <webElementGuid>800ab081-b7ce-4022-9cf2-aeac5b1d44d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'keyword_autoSuggestSelectedDiv' and (text() = '

Bangalore' or . = '

Bangalore')]</value>
      <webElementGuid>f1b47765-2869-4aa3-9a27-eac317d87d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div</value>
      <webElementGuid>7a40c0dd-af37-40d3-b8df-22cd1f7fe0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/following::div[5]</value>
      <webElementGuid>38348a3b-2fca-40d0-89f8-98ff7db6f400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/following::div[5]</value>
      <webElementGuid>274216ce-17e1-4227-82c6-bfe4967a63e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can enter'])[1]/preceding::div[3]</value>
      <webElementGuid>31c3baac-6aea-4e18-a104-1eaf336b6345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>68ce2f87-8c93-419f-98f3-8dd8402b1d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bangalore' or . = 'Bangalore')]</value>
      <webElementGuid>51d4ee39-94c2-4d05-baa0-f8395e0ce80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
