<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bangalore_mb-search__tag-close</name>
   <tag></tag>
   <elementGuidId>fd38aa66-f489-4feb-b9b7-db521725473b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__tag-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b829630c-2c9e-4405-924e-9a2321fc6b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tag-close</value>
      <webElementGuid>bd7e430f-3191-4f15-935a-f6e5f5ddd012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Bangalore</value>
      <webElementGuid>1c7af90c-0492-401a-9914-c99c913baddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3327</value>
      <webElementGuid>b5e8f27b-f4e2-4174-9797-7c8b8e94e809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)/div[@class=&quot;mb-search__tag&quot;]/div[@class=&quot;mb-search__tag-close&quot;]</value>
      <webElementGuid>181cb95a-743e-431b-af33-215f1a481413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div[2]</value>
      <webElementGuid>8a82bbb0-6aed-4d6c-8c12-8c5252da89eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]</value>
      <webElementGuid>791c22ca-af0f-4694-9bbc-203a6af292ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
