<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>eadfe658-4935-4a26-8648-336383d25058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='homepagePGSearchFormURL();fireHomeSearchGTM();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f98ca85d-57c5-4dc5-9834-382082f94524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__btn</value>
      <webElementGuid>804fd87c-aa68-4796-920c-d382bd78f42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>homepagePGSearchFormURL();fireHomeSearchGTM();</value>
      <webElementGuid>3a764bf2-d372-47ff-9214-c9541ebf58a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Search
</value>
      <webElementGuid>aee28b05-1175-445b-8cd1-8be630859873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormHolderSection&quot;)/section[@class=&quot;mb-search  mb-search-banner&quot;]/div[@class=&quot;mb-container&quot;]/div[@class=&quot;mb-search-container&quot;]/div[@class=&quot;mb-search__wrap&quot;]/div[@class=&quot;mb-search__btn&quot;]</value>
      <webElementGuid>0606e879-7dbc-4a16-940f-058316ea924c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>159e8187-3aa5-4a71-8135-1ec9847c87fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__btn</value>
      <webElementGuid>a7c0bb24-0624-4af9-8e90-3b22d12ccf63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>homepagePGSearchFormURL();fireHomeSearchGTM();</value>
      <webElementGuid>7bab9e4b-6126-4b5a-b9ff-65d5f9322f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Search
</value>
      <webElementGuid>6303e8a1-dedb-4191-a1f4-1eef99a0de40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormHolderSection&quot;)/section[@class=&quot;mb-search  mb-search-banner&quot;]/div[@class=&quot;mb-container&quot;]/div[@class=&quot;mb-search-container&quot;]/div[@class=&quot;mb-search__wrap&quot;]/div[@class=&quot;mb-search__btn&quot;]</value>
      <webElementGuid>6ce19f8e-c6f7-4bd2-a9dd-f7289fc794bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f047fb81-b9fe-4e6c-a7e9-3c2d035c354f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__btn</value>
      <webElementGuid>eb2c4035-1167-402b-903a-97efb16110c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>homepagePGSearchFormURL();fireHomeSearchGTM();</value>
      <webElementGuid>d9cb77e2-51b9-4829-8694-6873f56c8ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Search
</value>
      <webElementGuid>f0119863-3f0d-4425-9101-36870d9cd6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormHolderSection&quot;)/section[@class=&quot;mb-search  mb-search-banner&quot;]/div[@class=&quot;mb-container&quot;]/div[@class=&quot;mb-search-container&quot;]/div[@class=&quot;mb-search__wrap&quot;]/div[@class=&quot;mb-search__btn&quot;]</value>
      <webElementGuid>9e4aad41-0b65-4712-bc90-99aafcf2489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a71ad5b1-7ac8-43f0-a63a-592d7f4ba6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__btn</value>
      <webElementGuid>cc0d2f3a-8ff5-40ed-b228-38b6d418dbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>homepagePGSearchFormURL();fireHomeSearchGTM();</value>
      <webElementGuid>83d1ff6f-34f7-45a7-bbd9-e23f526c00b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Search
</value>
      <webElementGuid>32163fe2-c137-4d94-9172-2b3b690007ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormHolderSection&quot;)/section[@class=&quot;mb-search  mb-search-banner&quot;]/div[@class=&quot;mb-container&quot;]/div[@class=&quot;mb-search-container&quot;]/div[@class=&quot;mb-search__wrap&quot;]/div[@class=&quot;mb-search__btn&quot;]</value>
      <webElementGuid>3b635e44-8f38-4b62-b7c5-b30e473fc0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c324324b-16c6-4efb-907b-1840f63da056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__btn</value>
      <webElementGuid>c86fbd22-3158-47dd-8e6d-1033a4980c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>homepagePGSearchFormURL();fireHomeSearchGTM();</value>
      <webElementGuid>599aecdc-c350-458c-80ef-f3c304db12f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Search
</value>
      <webElementGuid>afcf6c37-1bbc-4f3d-a8d7-a4942adfc6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormHolderSection&quot;)/section[@class=&quot;mb-search  mb-search-banner&quot;]/div[@class=&quot;mb-container&quot;]/div[@class=&quot;mb-search-container&quot;]/div[@class=&quot;mb-search__wrap&quot;]/div[@class=&quot;mb-search__btn&quot;]</value>
      <webElementGuid>d4bb552d-b89f-4a91-946e-e126d25c84e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48211574-83f6-440b-8a60-236ac0c7f44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__btn</value>
      <webElementGuid>aff3ce75-6e7e-4deb-ba55-d8f6d772487c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>homepagePGSearchFormURL();fireHomeSearchGTM();</value>
      <webElementGuid>30db0071-95c3-48d9-a545-45e938210f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
 Search
</value>
      <webElementGuid>f2ef2537-42c8-4c57-8358-f8e2ad61ce5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormHolderSection&quot;)/section[@class=&quot;mb-search  mb-search-banner&quot;]/div[@class=&quot;mb-container&quot;]/div[@class=&quot;mb-search-container&quot;]/div[@class=&quot;mb-search__wrap&quot;]/div[@class=&quot;mb-search__btn&quot;]</value>
      <webElementGuid>3b1d348a-d49f-4f3c-8de4-0e9bfaeb2cdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='homepagePGSearchFormURL();fireHomeSearchGTM();']</value>
      <webElementGuid>c27c07bf-c945-421b-be17-5958f17ce4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[3]/div[4]</value>
      <webElementGuid>d846e9dc-c912-4c5e-965e-71e3e5125090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹20000'])[2]/following::div[1]</value>
      <webElementGuid>8b228a1f-9cc5-46b9-b4b4-2e335bd51c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹15000'])[2]/following::div[2]</value>
      <webElementGuid>da53adf6-caac-40b3-8b82-5645b9c1bbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a PG &amp; Hostel in Bangalore Away from Home'])[1]/preceding::div[7]</value>
      <webElementGuid>36774ac5-9358-4618-a59f-6387253c2108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Student Friendly PG', &quot;'&quot;, 's')])[1]/preceding::div[11]</value>
      <webElementGuid>51ce0f48-344b-434f-b801-994c485fb89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>1aff6eb1-30e3-4d4b-ae7f-b7dcbc52557b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]</value>
      <webElementGuid>c26726a1-e43b-4a6b-a13f-8d849b5d6f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
 Search
' or . = '
 Search
')]</value>
      <webElementGuid>e92b7197-4722-491e-ad4c-c1bcf3f83624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
