<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post Free Property Ad_keyword</name>
   <tag></tag>
   <elementGuidId>3655c442-2de8-434c-ba41-c8124751f896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68205dc0-8680-4d0b-8b4b-a8aaea042503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>b9f46399-97dc-49e5-a580-349066b22904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2b30d60-61a6-4b73-a80c-f89ab4def4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__input</value>
      <webElementGuid>0d62d670-2cac-4c36-9abc-5a598baf9c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter City, Locality, Landmark</value>
      <webElementGuid>d6593ede-832b-4c6e-b515-eed31a0faf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>showSearchHint(event, this); mb_hideCompactView('keyword');</value>
      <webElementGuid>e731a157-e4fa-4b29-8db0-2579fe06f388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8683ec4f-4d3b-499d-96b4-744989c5ee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>homepageAutoSuggest();</value>
      <webElementGuid>9ec2d6e5-71b5-468b-8b36-d72b794d77d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword&quot;)</value>
      <webElementGuid>d20dcb87-448c-4f74-81fd-f6acdb2ef428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b9ff4a4-e7a9-47d2-b82a-7dcac962bb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>63b2ceb9-4983-4c0b-900f-4b45c9cda713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fabe51b3-9fa9-4214-a09b-4985cd6961c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__input</value>
      <webElementGuid>ae1a4d3a-a57e-4ab9-862b-d1c316f059f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter City, Locality, Landmark</value>
      <webElementGuid>65627489-4652-4755-abe6-17b3ea7f8d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>showSearchHint(event, this); mb_hideCompactView('keyword');</value>
      <webElementGuid>03b27fb2-e569-4243-adb1-395964a1d62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>723b229c-90e0-4aad-9b5c-8a50d682ebb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>homepageAutoSuggest();</value>
      <webElementGuid>a44597db-3fe9-4ccc-bb05-1498eea4b4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword&quot;)</value>
      <webElementGuid>bb3cca36-d4d5-47e3-a385-97ad5cebc64a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keyword']</value>
      <webElementGuid>01d23cb9-eb8c-47a7-907e-a60937ce5a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/input</value>
      <webElementGuid>f3e6b1f3-cdfb-4dc1-bd99-d04ad29b4288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5790fda9-4b3a-4dfd-b260-875a8f2c415f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'keyword' and @type = 'text' and @placeholder = 'Enter City, Locality, Landmark']</value>
      <webElementGuid>c72e6d2c-1e34-4ae1-87bc-6b2574d379d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
