<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_bangalore</name>
   <tag></tag>
   <elementGuidId>ef633851-484a-442f-ba43-ebf84712363f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__auto-suggest__item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='serachSuggest']/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ad007f56-639f-4a32-a5c5-c602d0982a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bangalore</value>
      <webElementGuid>f210d04f-5de2-4276-bb17-1636301d6e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]/span[1]</value>
      <webElementGuid>85b3f140-f38f-4ac8-b433-5d72b64d9ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>87d32457-c2f1-4b2e-a440-aee0787185dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bangalore</value>
      <webElementGuid>d92f04ec-672b-4a9a-8475-bdb60863ed70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]/span[1]</value>
      <webElementGuid>bb95474b-80d7-48ba-a331-9d65359bd9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d82ce57-c195-41be-b789-b7052653d794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bangalore</value>
      <webElementGuid>6b060f0e-96d4-4f35-8906-16ddfd5e312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]/span[1]</value>
      <webElementGuid>51ba0cbf-171e-481b-a99e-5f809b983d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8dd89d2-9cdf-4ed3-9beb-2d3203e7c899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bangalore</value>
      <webElementGuid>d0c9b4f7-6482-4c5f-bf06-4122b448867e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]/span[1]</value>
      <webElementGuid>3e6aba8c-e54c-46c5-aba5-29ca8ce9161c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>baa67949-1b21-47be-b694-beefb4a2b786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bangalore</value>
      <webElementGuid>21f11977-3dcb-4a72-acef-698cd1fa813a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]/span[1]</value>
      <webElementGuid>20c24044-1b28-45c2-81d3-003960b56ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b86f80c4-c7dc-4012-9109-4843fb7e7dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bangalore</value>
      <webElementGuid>23d4e258-e2b2-4c34-8953-f6ce4461dfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]/span[1]</value>
      <webElementGuid>16999c0d-d442-426e-acc2-7b862efb9987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serachSuggest']/div[2]/span</value>
      <webElementGuid>f6173911-57d0-4b4b-86f3-a4de4966d9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::span[1]</value>
      <webElementGuid>d064c8eb-1c87-41ad-b8be-695217868da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Searches'])[1]/following::span[1]</value>
      <webElementGuid>80b434e8-6887-4901-bafb-397cd4e28010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bangalore'])[2]/preceding::span[1]</value>
      <webElementGuid>6fbf072c-73fe-4421-81cd-5e4f6a400213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bangalore']/parent::*</value>
      <webElementGuid>e9b28aa8-d3f6-4749-a5a2-8e1cc9ceb83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span</value>
      <webElementGuid>80e7c05d-223b-448b-b03a-cb96f0892bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'bangalore' or . = 'bangalore')]</value>
      <webElementGuid>f27803d6-6bac-49a1-b65f-c94fddded216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
