<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rent</name>
   <tag></tag>
   <elementGuidId>2c948616-a45e-40a6-a1a0-b0d68d3f87d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabRENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabRENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d6cec9c-6044-4072-8ab8-1a48e0504357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>eace33e8-25e7-4db8-9de4-36ba26dcffbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabRENT</value>
      <webElementGuid>b72333da-21ca-4247-b31c-b5de37ad2318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/residential-real-estate-Bangalore?category=R</value>
      <webElementGuid>a5ce0dfc-8bc5-4a3e-bf49-0ca6b7d2a85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'Rent');openPgTabUrl(this);</value>
      <webElementGuid>904ab0b2-1da7-4d54-bcf2-517c67ccc2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rent</value>
      <webElementGuid>3c18eb05-a32f-4fc6-9798-3a26aac1f6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabRENT&quot;)</value>
      <webElementGuid>9b0a02db-da26-4e7a-bfd3-7e4345e9f733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabRENT']</value>
      <webElementGuid>62b9c124-2387-40b7-a5c3-f539ac26f73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div[2]</value>
      <webElementGuid>0201481b-2d02-4162-b487-55c952ea9ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/following::div[1]</value>
      <webElementGuid>3e0ccf12-1987-40c1-a299-277f089ac4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='love'])[1]/following::div[3]</value>
      <webElementGuid>8b2402a6-6ea2-4363-bc50-f16c3f5a08e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[2]/preceding::div[1]</value>
      <webElementGuid>000529b9-0573-49b8-b30c-6be7f8b7aa03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plot'])[1]/preceding::div[2]</value>
      <webElementGuid>d9050a2a-14aa-4900-9b04-b57eb7d4458a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div[2]</value>
      <webElementGuid>ddb0a224-4b73-44c5-9dc2-7623c81aa507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabRENT' and (text() = 'Rent' or . = 'Rent')]</value>
      <webElementGuid>0ae3e9f5-adce-4393-9bfa-12037a61cfe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
