<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Find a home youll love</name>
   <tag></tag>
   <elementGuidId>2a749d83-f784-4c4c-a667-d23dd557dd04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home_page_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home_page_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>643b5415-9386-4296-a451-a2fdb6cfd27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__heading</value>
      <webElementGuid>0f61cf08-736c-4fb2-b302-59d3264ceccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_page_msg</value>
      <webElementGuid>12472bcb-b199-4037-819a-892b23015f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find a home you'll love</value>
      <webElementGuid>250e6a48-d29d-494e-903e-ddba29842378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_page_msg&quot;)</value>
      <webElementGuid>1a98d2e3-0c93-4edd-9f62-02e5b7c16def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home_page_msg']</value>
      <webElementGuid>6bc1d501-c61e-4304-b498-0ece09f2af17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div</value>
      <webElementGuid>c012e599-5dd6-4823-8d46-051520d21003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay your Rent'])[1]/following::div[3]</value>
      <webElementGuid>588b0a15-17dd-479a-bbfc-e1ca75b27212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Enquiry'])[2]/following::div[4]</value>
      <webElementGuid>3187fcdf-6c52-44d0-a6a9-13f0552d7f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/preceding::div[1]</value>
      <webElementGuid>be42d1bf-be3a-4f8c-9f83-92279c6302f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section/div/div/div</value>
      <webElementGuid>b01bb5de-effd-49d5-93b8-13d5327c172c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home_page_msg' and (text() = concat(&quot;Find a home you&quot; , &quot;'&quot; , &quot;ll love&quot;) or . = concat(&quot;Find a home you&quot; , &quot;'&quot; , &quot;ll love&quot;))]</value>
      <webElementGuid>6503c393-7cf3-4a9c-b134-0332f6f82506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
