<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Find your perfect Rental home</name>
   <tag></tag>
   <elementGuidId>824ade1b-1e1c-41d4-99b0-c7409597a153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home_page_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home_page_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>902e83d6-6fbc-49cb-a8f3-bf747900af02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__heading</value>
      <webElementGuid>1042549b-c721-49cc-acd1-e6c5e5fae438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_page_msg</value>
      <webElementGuid>b5a6ddf8-563f-4979-a1f1-8f29658982b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find your perfect Rental home</value>
      <webElementGuid>62461def-5526-42c0-9f98-1ba251eb95ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_page_msg&quot;)</value>
      <webElementGuid>d536fc1d-0d78-42d2-bf04-75bed81255af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db13b931-7136-4b52-bfae-30158b2df75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__heading</value>
      <webElementGuid>99f8e4fc-15e0-42d7-9e24-9a847d8ccbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_page_msg</value>
      <webElementGuid>aaa30a49-6325-4347-8adc-aa67cbea336a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find your perfect Rental home</value>
      <webElementGuid>c582b94f-d2be-475d-9ad4-7df193ce6bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_page_msg&quot;)</value>
      <webElementGuid>0a556e75-06b6-4c92-a3e3-5f23d48428b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home_page_msg']</value>
      <webElementGuid>233bc333-7345-41c2-b0ad-4994c7c26561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div</value>
      <webElementGuid>ddcecc11-e4d7-49bc-8d7d-b5afdbcef277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay your Rent'])[1]/following::div[3]</value>
      <webElementGuid>0dd1dc2a-b234-42cc-9e17-ee4ded1b1a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Enquiry'])[2]/following::div[4]</value>
      <webElementGuid>e865af3c-672f-4e09-b59a-7a8191a7b983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/preceding::div[1]</value>
      <webElementGuid>9702c480-dc75-4653-b37c-997064d67b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find your perfect']/parent::*</value>
      <webElementGuid>e652958b-c299-4f37-9ff4-904b15b8a0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section/div/div/div</value>
      <webElementGuid>55fcdbde-711c-4856-80e2-2912a5216cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home_page_msg' and (text() = 'Find your perfect Rental home' or . = 'Find your perfect Rental home')]</value>
      <webElementGuid>a3f4b949-57dc-4308-81f8-b8b1bc8bb37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
