<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Plot</name>
   <tag></tag>
   <elementGuidId>61d16638-cf06-4ec4-949f-f14e0e976471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabPLOT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabPLOT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ee749bd-ac0c-45e0-8398-ba3f5636ad46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>e7258adf-4933-4ab8-a445-c19f6815906e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabPLOT</value>
      <webElementGuid>429c4b89-8733-4b6d-a42f-f738b6712fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/Plots-Land-Bangalore</value>
      <webElementGuid>529bf4d2-dd38-4911-8d21-515a65ec558d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'Plot');openPgTabUrl(this);</value>
      <webElementGuid>c097be52-f57d-4f8e-b69c-1be64a630183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plot</value>
      <webElementGuid>650b95a7-c764-4e11-b90f-98f6a44a8cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPLOT&quot;)</value>
      <webElementGuid>4e4276cd-f1ee-431e-b682-083b02d2d120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabPLOT']</value>
      <webElementGuid>491c3dc3-3603-4961-b90e-d0474ffdd48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div[4]</value>
      <webElementGuid>69e788b4-0960-43af-bae6-c8ff640d9ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[1]/following::div[1]</value>
      <webElementGuid>15514c08-6cbe-44e2-ad6f-b47a0d5f6846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent'])[2]/following::div[2]</value>
      <webElementGuid>bd451adc-656c-4ad9-aeb7-9f7e0e4d33d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/preceding::div[1]</value>
      <webElementGuid>74e4a23c-2990-4c46-b667-97e57039810d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/preceding::div[2]</value>
      <webElementGuid>55978b95-7175-4925-a181-9342bd9ce6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Plot']/parent::*</value>
      <webElementGuid>5c2c3b79-9dcd-43c9-967f-3f68c45f54d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div[4]</value>
      <webElementGuid>3b811f6b-a0aa-4407-8f9d-5a1af9cd10d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabPLOT' and (text() = 'Plot' or . = 'Plot')]</value>
      <webElementGuid>8e783e87-2a71-46bc-bc70-dfd8bf28241e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
