<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rent</name>
   <tag></tag>
   <elementGuidId>ca657ead-413c-4860-96bb-2a6e990332d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabRENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabRENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec29e2a1-a19e-449c-9ab2-aee91f84ef1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>0ee204b0-88b1-4126-9d24-0b3b59a022ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabRENT</value>
      <webElementGuid>56dab57f-ad97-4e17-9e60-c6d2bc2f81b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/residential-real-estate-Bangalore?category=R</value>
      <webElementGuid>cd276448-3f5f-4096-a565-8c87e5c8cbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'Rent');openPgTabUrl(this);</value>
      <webElementGuid>bacf5c68-f59b-42c6-bc68-3a5ef4516388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rent</value>
      <webElementGuid>0c9d8963-568b-4b71-8314-4a172de01903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabRENT&quot;)</value>
      <webElementGuid>a92baa81-498a-4ba9-a728-6220eb110eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabRENT']</value>
      <webElementGuid>fe205dcb-83da-4e5d-bfe5-1ef4d2e03009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div[2]</value>
      <webElementGuid>21a8c89c-6dac-489f-b5ed-5aedd1365de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/following::div[1]</value>
      <webElementGuid>e670070b-361d-4f7c-9c01-f45352dd4e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='love'])[1]/following::div[3]</value>
      <webElementGuid>c8fdcb5d-0752-44a3-9bfd-9e75a407d043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[1]/preceding::div[1]</value>
      <webElementGuid>676814ce-c994-4237-9b76-5db662f22191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plot'])[1]/preceding::div[2]</value>
      <webElementGuid>f7e8dfde-961e-4120-9e86-a4daad42944a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div[2]</value>
      <webElementGuid>8815bd40-47fc-40bb-aa4d-e5bb59d58d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabRENT' and (text() = 'Rent' or . = 'Rent')]</value>
      <webElementGuid>bc74d1c2-98f7-4356-85e5-a7e905d908f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
