<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Post Property Free</name>
   <tag></tag>
   <elementGuidId>0571e167-99ab-402a-8e88-f00eb6985b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;trackGaEventInGLobalNav('76');trackThisData();&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.font-type-4.fo_13px</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c79f80d7-fb36-4575-b212-4d8d2ad763a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>trackGaEventInGLobalNav('76');trackThisData();</value>
      <webElementGuid>d16de824-8d9d-4190-be1f-07e7dcdc443e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://post.magicbricks.com</value>
      <webElementGuid>43dad7f4-9587-47d0-ad58-e6b24d715561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-type-4 fo_13px</value>
      <webElementGuid>c844e9c1-03eb-421f-ad35-ca211668bd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a5d3e71d-a893-47d2-a53d-dc7484548811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post Property Free</value>
      <webElementGuid>26fc084d-1391-4dfd-ab4f-4b4ee5de41c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/header[@class=&quot;main-header&quot;]/div[@class=&quot;dataContainer&quot;]/div[@class=&quot;headerRightCont&quot;]/div[@class=&quot;right_link_group&quot;]/div[@class=&quot;postProperty&quot;]/a[@class=&quot;font-type-4 fo_13px&quot;]</value>
      <webElementGuid>d0de2f64-9674-4978-a4b2-1050bfed00de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;trackGaEventInGLobalNav('76');trackThisData();&quot;]</value>
      <webElementGuid>58db8c37-be9e-4943-97a4-b95b64abff1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/header/div/div[3]/div[2]/div[2]/a</value>
      <webElementGuid>271ab21b-6d09-492f-89d0-c85ecd630db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See More Magicbricks Apps'])[1]/following::a[1]</value>
      <webElementGuid>ae6781da-9b60-483a-bc47-4e6e4c7b52d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[4]/following::a[1]</value>
      <webElementGuid>20afeb74-e914-41d5-83f2-136af56d9ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Post Property']/parent::*</value>
      <webElementGuid>22d518ea-0700-4d88-86b6-00468de58667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://post.magicbricks.com')]</value>
      <webElementGuid>f8dea67e-15ed-40d7-8992-deec0dfa957a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>dfc1136e-2e9f-4973-bad6-9c48191a020d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://post.magicbricks.com' and (text() = 'Post Property Free' or . = 'Post Property Free')]</value>
      <webElementGuid>f0686ea9-3211-4f4e-8ae1-2816debd73ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
