<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Submit_oppPopup_close md-close</name>
   <tag></tag>
   <elementGuidId>55654c47-fc46-4c55-998f-e63b900bd2d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;trackingPopupClose('PostPropLandingPopup');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popupjsp > a.oppPopup_close.md-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b617cd2e-3256-4c18-82f4-65d112a4a701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ppPopupClose('PostPropLandingPopup')</value>
      <webElementGuid>25c9cef3-51bf-43c9-b4af-8ef7034e690a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>trackingPopupClose('PostPropLandingPopup');</value>
      <webElementGuid>b3ea1ab7-7289-45af-bef8-e2573a953c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oppPopup_close md-close</value>
      <webElementGuid>f401aaed-c679-4d78-bd2e-7523bce44fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupjsp&quot;)/a[@class=&quot;oppPopup_close md-close&quot;]</value>
      <webElementGuid>c1940e85-23c1-45f0-8fba-503795d1c46f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;trackingPopupClose('PostPropLandingPopup');&quot;]</value>
      <webElementGuid>968ddb90-2334-404b-a96f-a5a824289ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupjsp']/a</value>
      <webElementGuid>d68f0aff-1573-40d6-abac-cdc9d8ff163b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ppPopupClose('PostPropLandingPopup')&quot;)]</value>
      <webElementGuid>b153cd57-0314-43ec-b9fd-4eb5fcf90b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>0d8da69a-ef73-4c50-86d8-50e89b37d754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:ppPopupClose(&quot; , &quot;'&quot; , &quot;PostPropLandingPopup&quot; , &quot;'&quot; , &quot;)&quot;)]</value>
      <webElementGuid>9d5c11d3-3e38-4340-ac71-05b61601fe0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
