<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PG</name>
   <tag></tag>
   <elementGuidId>acccdd79-3c99-4178-996a-59fb2919e256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabPG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabPG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff16409d-4cd7-40af-b6f7-92e622029c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>aef6f6f1-1fc7-4dff-b94f-5e4da3f66475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabPG</value>
      <webElementGuid>ea843889-e0b8-4f9c-9b01-1d284d538381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/pg-hostels-Bangalore</value>
      <webElementGuid>12921571-9744-450a-a7fe-96613bd63e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'PG');openPgTabUrl(this);</value>
      <webElementGuid>e70d52a9-71e8-4942-b3bc-4994ef65b0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PG</value>
      <webElementGuid>63c7665c-e9ae-499d-8bb7-b8e9b7c8be72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPG&quot;)</value>
      <webElementGuid>0102bdc4-906b-4539-ac4d-371e433e2df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a54a090-e1ad-4bf9-b694-e8d2a16c508b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>753f6e3c-3c17-43fc-9752-ef5663bd42fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabPG</value>
      <webElementGuid>355ec738-651a-4ce3-8913-c2b490b7019f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/pg-hostels-Bangalore</value>
      <webElementGuid>edd7b561-ec34-4ef1-9fdd-9bd5a9a062f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'PG');openPgTabUrl(this);</value>
      <webElementGuid>16736eef-9b87-4121-ad55-640994e818e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PG</value>
      <webElementGuid>39832e7b-f033-41bd-b087-f4992516d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPG&quot;)</value>
      <webElementGuid>0a4022b5-fd7f-4810-a8c5-384005955fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabPG']</value>
      <webElementGuid>a45343a4-6987-4b16-9024-cffdc2d21bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div[3]</value>
      <webElementGuid>148ccd46-5533-4c93-a417-5cb782f8f94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent'])[2]/following::div[1]</value>
      <webElementGuid>e5099551-611f-40b3-a3ad-0205dd2eb051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/following::div[2]</value>
      <webElementGuid>5e53b0f9-1363-4be4-bf5e-7c35cc4b7f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plot'])[1]/preceding::div[1]</value>
      <webElementGuid>d6d3904f-6095-4cef-80dc-9b603d36bc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[3]/preceding::div[2]</value>
      <webElementGuid>e4fd10c9-6f7b-4921-8ba2-db57357bd43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div[3]</value>
      <webElementGuid>292f719f-13ee-453a-a49a-fcdfde2a07db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabPG' and (text() = 'PG' or . = 'PG')]</value>
      <webElementGuid>03567444-401e-43e4-864e-abf507047426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
