<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bangalore_mb-search__tag-close</name>
   <tag></tag>
   <elementGuidId>50ca97fb-6e9d-4442-9229-2cd6ae1168c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__tag-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>397612a7-5cdf-41df-af8d-b345ef0f8346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tag-close</value>
      <webElementGuid>9b891b1b-110f-4222-91c3-071bcc77dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>Bangalore</value>
      <webElementGuid>c211f1a1-d2cc-476d-90b7-9cc28d5609a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3327</value>
      <webElementGuid>12f423af-fe80-4b0b-87c9-cb06883c21c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)/div[@class=&quot;mb-search__tag&quot;]/div[@class=&quot;mb-search__tag-close&quot;]</value>
      <webElementGuid>f4423ebf-a1a1-4cdc-8ee2-5e5458e918d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div[2]</value>
      <webElementGuid>b8c1b4ff-6c05-457a-8b20-8e0d2e3e9c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]</value>
      <webElementGuid>7d4bef03-ca3f-47c7-81bb-29a28628243d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
