<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Buy</name>
   <tag></tag>
   <elementGuidId>d90c9a6a-179b-432f-905b-48c929803d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabBUY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabBUY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>566891a6-9e7f-40dd-b5a3-2710ce97fe6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>8bbc4d49-b5d7-42f6-ac22-277b46ede38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabBUY</value>
      <webElementGuid>d556c49e-b0d2-47f8-a8a5-359fcab1642a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/residential-real-estate-Bangalore?category=S</value>
      <webElementGuid>04b8c060-a863-4380-912d-94229819485a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'Buy');openPgTabUrl(this);</value>
      <webElementGuid>416eb998-564d-4884-b237-2832ee176200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>0aae2fd5-a09c-482c-8045-a553ce223a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabBUY&quot;)</value>
      <webElementGuid>a684b0b4-e33b-4fab-a3c0-0eafb65931d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabBUY']</value>
      <webElementGuid>25f46560-2f2f-42bb-9500-153335fb09d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchFormHolderSection']/section/div/div/div[2]/div</value>
      <webElementGuid>7494a67e-5da8-4564-8643-9346673dbea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='home'])[1]/following::div[2]</value>
      <webElementGuid>2738108a-ddb2-412a-bd18-56c3414c6eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent'])[2]/preceding::div[1]</value>
      <webElementGuid>595fa1e2-a568-4f83-95a4-663001029bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[1]/preceding::div[2]</value>
      <webElementGuid>5ff97d5e-3094-4288-8462-60d81b419c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div</value>
      <webElementGuid>f67a977e-a76e-423d-9062-693b3b425f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabBUY' and (text() = 'Buy' or . = 'Buy')]</value>
      <webElementGuid>04ab4ee6-e17e-4cdb-b952-4bff5f5f3a08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
