<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bangalore</name>
   <tag></tag>
   <elementGuidId>d1171edc-33e0-48f1-9430-3a4fbb103736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__tag-t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdcd960b-b62f-4413-b13c-0abc5e26c1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tag-t</value>
      <webElementGuid>54f26bdb-b2e1-4d30-a057-13059b641754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3327</value>
      <webElementGuid>89146ef6-afaf-403a-965f-f3ca01c155ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bangalore</value>
      <webElementGuid>4d53180b-1a47-438f-a444-f3a392e5f411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_autoSuggestSelectedDiv&quot;)/div[@class=&quot;mb-search__tag&quot;]/div[@class=&quot;mb-search__tag-t&quot;]</value>
      <webElementGuid>b2dec355-3dac-41ff-abc9-fa40d596c7b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/div/div</value>
      <webElementGuid>827275f9-b744-4c2a-b912-bfe126f29505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/following::div[5]</value>
      <webElementGuid>6dc86ca2-063c-4216-801f-47e40a985473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial'])[1]/following::div[5]</value>
      <webElementGuid>577bd107-08d6-43ad-afd4-4ae736f82391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can enter'])[1]/preceding::div[3]</value>
      <webElementGuid>7b8b6e34-8418-41fe-ae4e-3d9d190dad7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div</value>
      <webElementGuid>05156cd5-84fe-4840-aa87-0b192356789d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bangalore' or . = 'Bangalore')]</value>
      <webElementGuid>32be61a9-b6c4-46a0-948b-819225a9ac43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
