<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_noida</name>
   <tag></tag>
   <elementGuidId>3da63f59-07b0-4702-b86b-bfeb7964d562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-search__auto-suggest__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='selectSearch(&quot;Noida&quot;,6403,6403,&quot;city&quot;)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd9d6cec-4875-46c4-bf49-2af2d0a13335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__auto-suggest__item</value>
      <webElementGuid>2cefd0e3-d9be-4cb2-8714-ecc4559c60c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectSearch(&quot;Noida&quot;,6403,6403,&quot;city&quot;)</value>
      <webElementGuid>05d02edb-73b5-4383-abbb-afd5cd4e3939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>noida</value>
      <webElementGuid>b36a7c4e-58c7-4284-9e7f-d4314b56919f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serachSuggest&quot;)/div[@class=&quot;mb-search__auto-suggest__item&quot;]</value>
      <webElementGuid>91b97011-af91-489b-be6f-a251f901f179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='selectSearch(&quot;Noida&quot;,6403,6403,&quot;city&quot;)']</value>
      <webElementGuid>4893c26f-0f06-4db3-acb5-b3e3cd15fdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serachSuggest']/div[2]</value>
      <webElementGuid>dc097247-5844-4a92-88b3-8c70321d2ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::div[1]</value>
      <webElementGuid>3c3c4eeb-184b-41b3-a4b4-4a9e6c782930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Searches'])[1]/following::div[4]</value>
      <webElementGuid>e842cd4a-d195-41c7-a429-2fcb65a22c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]</value>
      <webElementGuid>b7b4a843-b19c-4af0-a140-877a23830ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'noida' or . = 'noida')]</value>
      <webElementGuid>ab9bce5b-27ff-4965-8d2f-723adf110aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
