<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post Free Property Ad_keyword</name>
   <tag></tag>
   <elementGuidId>5d68a5a4-86d7-4679-89b7-09e9878f04c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5c9b759-d465-496e-a3b1-92eef9ff629f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>9d821421-7f14-4644-a1cb-21a54d4f22d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc39da2f-fda3-42cd-8530-23f00ecd9b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__input</value>
      <webElementGuid>db9e98d9-2f3d-428d-9917-fddbe771f113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter City, Locality, Landmark</value>
      <webElementGuid>74abdf5c-d252-4f42-9642-f7923a858539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>showSearchHint(event, this); mb_hideCompactView('keyword');</value>
      <webElementGuid>4dfd4eaa-faa4-4adc-9dfd-268a63869ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9a4840a-a063-485f-bf52-a66eaafd5a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>homepageAutoSuggest();</value>
      <webElementGuid>a0a9ed75-c28d-4c9b-9359-deff6de49757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword&quot;)</value>
      <webElementGuid>72e772ed-e869-4d8a-96e0-620b46cd568b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keyword']</value>
      <webElementGuid>adeb3b2a-6289-4b68-895b-de0f1770df5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keyword_autoSuggestSelectedDiv']/input</value>
      <webElementGuid>96c5fa55-f66f-4af1-a5e2-1a2e7a470b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>829af78a-ed2a-4a45-848b-e04998b56061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'keyword' and @type = 'text' and @placeholder = 'Enter City, Locality, Landmark']</value>
      <webElementGuid>1f08fc0b-7dbc-4fc3-864d-33eccf04c7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
