<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Enter Email ID or Mobile No</name>
   <tag></tag>
   <elementGuidId>08683b87-a03d-4d1d-81c5-072093a229d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='firstLoginDiv']/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.m-login__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3d501835-4c3c-4f52-afb9-39286203e055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-login__label</value>
      <webElementGuid>eee6c88d-de9f-4939-889f-90b0fe8f8deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>emailOrMobile</value>
      <webElementGuid>60982fe4-747c-4611-9707-48cefed5bde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Enter Email ID or Mobile No.
			</value>
      <webElementGuid>a431b713-7f2c-480e-8de2-a1e6fbbc2584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstLoginDiv&quot;)/div[@class=&quot;m-login&quot;]/div[@class=&quot;m-login__fieldset&quot;]/label[@class=&quot;m-login__label&quot;]</value>
      <webElementGuid>da87f2b1-4599-4d46-af7a-6dc1eba93151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='firstLoginDiv']/div[2]/div/label</value>
      <webElementGuid>8325b21a-7abd-4b94-9c96-71563e006157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::label[1]</value>
      <webElementGuid>82d4873b-36ce-4869-9a94-5285aaaa9b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add detailed property information &amp; multiple photos per listing'])[1]/following::label[1]</value>
      <webElementGuid>f8ee1b72-f39c-46de-b740-3be3f7642793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::label[1]</value>
      <webElementGuid>9d2f3beb-b271-4b53-a23c-3963cc401fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/preceding::label[1]</value>
      <webElementGuid>ca263e32-3c13-4bca-84b4-c5177ef0e3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Email ID or Mobile No.']/parent::*</value>
      <webElementGuid>9a377c13-2069-4fed-ad1e-44379debe987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>b10fc754-ee26-4630-84fa-a5b3e88564f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
				Enter Email ID or Mobile No.
			' or . = '
				Enter Email ID or Mobile No.
			')]</value>
      <webElementGuid>f24caaff-e387-40f5-88fe-0f069d8ce9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
