<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Move into Test, a professionally manage_c6d4f7</name>
   <tag></tag>
   <elementGuidId>8a395591-a2fc-4e1d-b2b7-66911a8e450c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pgDescSample1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pgDescSample1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cb87ddd-3e1f-4581-b4b9-4100fbe1108a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__card__more-content</value>
      <webElementGuid>3cd7c540-a115-459e-b0d8-baa7d04e36be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgDescSample1</value>
      <webElementGuid>d0157bb1-36e2-45f6-a7a2-99b14fd84021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Move into Test, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.</value>
      <webElementGuid>a11c3859-281a-452b-a165-e168d147c9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgDescSample1&quot;)</value>
      <webElementGuid>1a5f5d89-1662-4fe3-bcb1-acda72ba9dc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pgDescSample1']</value>
      <webElementGuid>cb2cdd4c-4bc1-4408-a416-1b21a167834b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-moredetails']/div/div[5]/div[3]/div[2]</value>
      <webElementGuid>3cf3736b-34d1-4389-924d-21de300e3993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample 1'])[1]/following::div[1]</value>
      <webElementGuid>88077fe0-f649-49c5-9e4f-5fa523e2ce49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample Description'])[1]/following::div[3]</value>
      <webElementGuid>c4ce0f2b-fa7a-449b-9297-3c05c484a35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit &amp; Use'])[1]/preceding::div[1]</value>
      <webElementGuid>d476ff17-d7a3-446d-a153-69246d2680c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample 2'])[1]/preceding::div[2]</value>
      <webElementGuid>db1db6c8-4940-43e2-8e77-9815e836863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Move into Test, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.']/parent::*</value>
      <webElementGuid>01881b35-9395-4f00-a4d1-dd4f25f0fc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]</value>
      <webElementGuid>a74e088c-9d4f-45c2-b6df-5817cbf6d911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pgDescSample1' and (text() = 'Move into Test, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.' or . = 'Move into Test, a professionally managed PG home in the Long Island, Andaman and Nicobar. Located in a safe neighborhood, this female PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.')]</value>
      <webElementGuid>d9000d98-50c7-4857-9ae0-1c7decadb992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
