<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Field Agent will be visiting you so_c9017e</name>
   <tag></tag>
   <elementGuidId>9cb02ae9-546f-45fa-a0db-6367e6351f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>433e6013-da6f-4cf6-bedb-cc6073131b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-close</value>
      <webElementGuid>43c4b880-008a-41d3-b9e3-23a438a384f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closePopup('pgpckgPopup')</value>
      <webElementGuid>a4c2aebb-c662-4665-a7c3-95b278090d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgpckgPopup&quot;)/div[@class=&quot;m-popup__table&quot;]/div[@class=&quot;m-popup__table-cell&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;m-popup__content&quot;]/div[@class=&quot;m-close&quot;]</value>
      <webElementGuid>44bc00f6-401b-4fdb-9606-dfdce3512522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      <webElementGuid>3d332660-629d-473f-a745-a447dbd578ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgpckgPopup']/div/div/div/div/div</value>
      <webElementGuid>473d34bd-02a4-4cdf-a810-32724c6391b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>f502b35c-f73e-481f-a59e-93622e217565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
