<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make sure you enter the correct addre_b9e526</name>
   <tag></tag>
   <elementGuidId>8a3c5f1f-faba-4f64-ae07-8f92ba2ee6cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedLocality']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedLocality</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b1d4d2-4991-46d9-bcd9-8603f23e31cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__slide__location__input js-autosuggest</value>
      <webElementGuid>9dc38f0d-9067-49a9-ac8d-44777663925a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5de4dba1-c0b5-494a-8c49-c7443f7c8c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Locality</value>
      <webElementGuid>7c94200b-aa0e-492b-b4f1-83b8217d19e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>16ab5554-ee2e-49d4-9896-3d004d3d80fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>9b356187-c4ff-4e8c-8289-8921d42b9e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLocality&quot;)</value>
      <webElementGuid>e501fe7f-67b0-496d-a5d7-0372c8925c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedLocality']</value>
      <webElementGuid>c6b37869-72ce-4c3a-9e34-1d9bdc3587f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-location']/div/div[3]/input</value>
      <webElementGuid>393081e2-0f6f-43d5-9853-caaf8ef9261a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c3ae8c7f-4413-4170-a5a1-9862db46e80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Locality' and @id = 'selectedLocality' and @name = 'selectedLocality']</value>
      <webElementGuid>f15577dc-f72e-4371-94f8-04046f1ceb76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
