<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rentPerBed_16011</name>
   <tag></tag>
   <elementGuidId>f30da469-d3af-4213-a383-9ba61cffc8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rentPerBed_16011']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rentPerBed_16011</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31312a05-5292-42ed-91d0-52a456ffb2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>d582543e-2f34-4be5-b9da-4bfc079e3db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1af0c72b-bcc0-4de3-9fa4-ee74c34bb492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rentPerBed_16011</value>
      <webElementGuid>7f94afe4-b2cb-4ac6-a2a0-d10560020ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rentPerBed_16011</value>
      <webElementGuid>e31f1215-0c5f-40e8-93da-5dfdda589118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a8b04c61-58d3-41f7-bc98-f0ad5fe68bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>86414588-63f1-405f-bf95-b42b0d141331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rentPerBed_16011&quot;)</value>
      <webElementGuid>52afa419-c12f-430c-899a-c91967f55881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rentPerBed_16011']</value>
      <webElementGuid>e12b4bac-44c2-4971-933d-6bf0e92f8c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roomDetail_16011']/div[3]/div/div[2]/input</value>
      <webElementGuid>fc4ed1c5-8cf8-4948-a739-984e7c722261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>cb429e5b-94f8-4d38-a8ae-ceb9c096c4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'rentPerBed_16011' and @id = 'rentPerBed_16011']</value>
      <webElementGuid>e928cf80-e89d-4d3f-9721-d7352da6eaf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
