<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Single Room_noOfRoom_16011</name>
   <tag></tag>
   <elementGuidId>178e9138-f3c2-4d69-9520-ff923e385b6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noOfRoom_16011']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#noOfRoom_16011</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43c2b60f-1506-4dce-943a-7d46914b1029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>cb46acda-6f93-4cfe-a710-586e66da8635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>728b2cb9-8c71-4cd0-a9a6-2cc1510ff91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noOfRoom_16011</value>
      <webElementGuid>be0b4e83-f1b8-46c6-86e3-59212c9b9645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noOfRoom_16011</value>
      <webElementGuid>9b0805a8-195d-4af0-88cd-cea2f12e698c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>35a93853-53c3-4574-ad03-b3e3acb9ec2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>7973cbf8-47a5-458d-bed7-b5edca4644c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noOfRoom_16011&quot;)</value>
      <webElementGuid>5ce4f699-0cd1-438c-8b3f-8a3536c85561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noOfRoom_16011']</value>
      <webElementGuid>d385e020-2555-4aa4-b08e-6e3fac056770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roomDetail_16011']/div[3]/div/div/input</value>
      <webElementGuid>3a20658f-f18d-47ec-9cfa-73c6f43f3d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>53b5aa98-b84c-4918-838a-4a60c3425598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'noOfRoom_16011' and @id = 'noOfRoom_16011']</value>
      <webElementGuid>1090542b-5729-4545-b7b5-a673e2b2763f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
