<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pglandmark</name>
   <tag></tag>
   <elementGuidId>6a58541b-aac6-4716-8ed5-1db5ce768bbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pglandmark']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pglandmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d513281-bd88-4119-a661-8803cc23a39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>8aba7e80-6a02-423e-b95a-b46b35d19c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7512d08b-07bc-4a58-874e-0c6edb2e8516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pglandmark</value>
      <webElementGuid>d01c0060-4284-4cb2-9415-14ff6996509d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pglandmark</value>
      <webElementGuid>573093fd-5fc4-44ec-b56d-7e32ca1e2c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pglandmark&quot;)</value>
      <webElementGuid>196042e7-86db-4fc5-b915-1000ed1dee8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pglandmark']</value>
      <webElementGuid>f3cfe277-5607-43be-a3c8-b53ec93763e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-address']/div/div[4]/div[5]/input</value>
      <webElementGuid>e586e411-f182-42d4-8a04-22eb92fc02a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>c9a1f6e9-05ac-406f-b1b8-3b5d248559cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pglandmark' and @name = 'pglandmark']</value>
      <webElementGuid>e0bbde0f-c325-44ed-a2d8-63aacaa9630b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
