<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Add PhotoSingle RoomRequired Cover photo_3c03f3</name>
   <tag></tag>
   <elementGuidId>a87ef2a9-4c46-4710-91a6-67c25aef106d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='overviewsection_37602']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overview_37602</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0297f9d6-8d66-4a0b-8b70-9245c7955216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-pic__category__list--item</value>
      <webElementGuid>55ab277b-5713-4778-b40a-954b86e26f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overview_37602</value>
      <webElementGuid>dc098ff2-698b-49e1-ab3b-4d3d2718ea41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add PhotoSingle RoomRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.</value>
      <webElementGuid>a286475c-f117-49ca-93cd-2f5286aa4682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview_37602&quot;)</value>
      <webElementGuid>f6bd4906-a049-4c70-994d-b66894fe0d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='overview_37602']</value>
      <webElementGuid>36e093f0-fe3c-4204-85a5-e3e36678e7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='overviewId']/li</value>
      <webElementGuid>271379c9-6288-4fe3-93ec-23e856ab2a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li</value>
      <webElementGuid>c0585081-826a-497a-9d2e-f23356ef9192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'overview_37602' and (text() = '+Add PhotoSingle RoomRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.' or . = '+Add PhotoSingle RoomRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.')]</value>
      <webElementGuid>e219f601-f846-4956-a790-f8358d7b5ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
