<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Add PhotoBuilding ViewRequired Cover pho_8053b1</name>
   <tag></tag>
   <elementGuidId>ae62d1e9-ccbd-4e07-b7c4-23efd4da4d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#overview_37601</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='overviewsection_37601']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6b283665-68fe-40e3-aa4f-f74ad0839e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-pic__category__list--item</value>
      <webElementGuid>13095173-402d-4664-9b93-437e7f9a77f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overview_37601</value>
      <webElementGuid>96b1d361-18ed-453d-8d78-6bc6b3bef9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add PhotoBuilding ViewRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.</value>
      <webElementGuid>a91cd61b-2bb4-42d7-82d5-caa4bb781a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview_37601&quot;)</value>
      <webElementGuid>28ad76e3-d520-4f79-8baf-41d76daa8101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='overview_37601']</value>
      <webElementGuid>df358222-6fb7-46ce-a0c7-ccfe6feb3aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='overviewId']/li[2]</value>
      <webElementGuid>61f4dc2d-643f-4b2b-be6e-657f1f277add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover photo'])[1]/following::li[1]</value>
      <webElementGuid>ac16617b-756c-413f-9fc7-0006d94d79d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[31]/following::li[1]</value>
      <webElementGuid>2315f589-2c9e-4b93-863a-846294c2d104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[2]</value>
      <webElementGuid>d1ca14c2-187c-458d-9c5c-e9fe1b7575d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'overview_37601' and (text() = '+Add PhotoBuilding ViewRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.' or . = '+Add PhotoBuilding ViewRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.')]</value>
      <webElementGuid>54e5cbce-4ba4-4342-a7af-6f3622b23e64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
