<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Long Island, Andaman  Nicobar</name>
   <tag></tag>
   <elementGuidId>2136ba2c-d5c2-4944-95b0-68f7cfbc2ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='locality_options']/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.js-dropdown-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>25949f74-39e8-414b-ad3b-1c057af0723c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-dropdown-element</value>
      <webElementGuid>b92d4dce-d403-42af-8c12-d772a8123cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-city</name>
      <type>Main</type>
      <value>7058</value>
      <webElementGuid>aec0b7c4-d486-4972-a32c-e559f8ba5f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>b45fff03-8779-4163-9bd9-f3b5c904b208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locality</name>
      <type>Main</type>
      <value>Long Island, Andaman &amp; Nicobar</value>
      <webElementGuid>860d67bc-d032-4574-ae56-29220931a1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-latitude</name>
      <type>Main</type>
      <value>12.4051021</value>
      <webElementGuid>ebd77f5b-3d36-4d79-835e-bc39acfc7478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-longitude</name>
      <type>Main</type>
      <value>92.9325785</value>
      <webElementGuid>b304ba9a-09cd-4c64-946e-73f21a974604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lmtrfnum</name>
      <type>Main</type>
      <value>74979</value>
      <webElementGuid>77072bfb-67f5-45dc-8e4d-86869fa666e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Long Island, Andaman &amp; Nicobar
							</value>
      <webElementGuid>a52e66df-9673-47d3-893a-a6c5abe42fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locality_options&quot;)/li[@class=&quot;js-dropdown-element&quot;]</value>
      <webElementGuid>80ddd735-edab-428a-b5a4-93b6b20f5000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='locality_options']/li</value>
      <webElementGuid>1bf6ffa8-d545-4cc4-97fc-6e0c9e86fe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure you enter the correct address for a smooth verification.'])[1]/following::li[1]</value>
      <webElementGuid>a4d72f3f-1b6f-4855-bfcd-4c2807627c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where is your PG Located?'])[1]/following::li[1]</value>
      <webElementGuid>7def84ca-0083-4a5d-b392-d4d9638317b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Long Island,']/parent::*</value>
      <webElementGuid>ee420416-28ad-4e81-ae9c-57218f5b7fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>09d9b570-0c75-46f8-a680-fe71807cb0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
								Long Island, Andaman &amp; Nicobar
							' or . = '
								Long Island, Andaman &amp; Nicobar
							')]</value>
      <webElementGuid>f767ae04-74d0-41d7-90e9-f209319bda72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
