<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tell us more about your PG_pgdescription</name>
   <tag></tag>
   <elementGuidId>36444f51-162a-4892-bc0a-27c1af603fe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pgdescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pgdescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4030a69d-fd5d-4fda-b5cd-b6a5f1cd3561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input mb-form__textarea</value>
      <webElementGuid>9fe44e75-a122-42c8-adfd-6840533511fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>mbPgUi.autoGrow(this)</value>
      <webElementGuid>3be1047a-79af-43df-ac3c-116718dd14c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgdescription</value>
      <webElementGuid>1b9df78c-d2b0-4bac-b383-7b1e338a8f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgdescription</value>
      <webElementGuid>c114b66b-e637-4506-b67c-597610f733cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgdescription&quot;)</value>
      <webElementGuid>8962be5a-5fb8-4009-b2eb-a7d4398ff93b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pgdescription']</value>
      <webElementGuid>bf234739-3c57-4c16-8014-fcf4ef7ec508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-moredetails']/div/div[3]/div/textarea</value>
      <webElementGuid>a6f53b88-5062-4416-a4be-95f4da423ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2a05f834-850b-4e67-930a-584f9c0bfa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pgdescription' and @name = 'pgdescription']</value>
      <webElementGuid>29381c31-7eb9-44b7-8c34-fb26898441a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
