<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Type_propertyTypeVal</name>
   <tag></tag>
   <elementGuidId>8c3314a9-46cf-42ab-bb19-eded3c0cae0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyTypeVal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propertyTypeVal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45cae682-3ebe-48bc-95c0-6535e0c926e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>adb87941-2b8a-4e39-92d7-804da9d8d2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyTypeVal</value>
      <webElementGuid>c6833fc2-5569-49ee-bdb6-ec8a0aa7477d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyTypeVal</value>
      <webElementGuid>fccb8d9f-1716-4c48-9ac1-caba3f787e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Select Property Type</value>
      <webElementGuid>ff98539d-98b2-4ae4-9c77-7604babe6f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ciDrop btnInput</value>
      <webElementGuid>dc1d8f93-bc42-42dc-9fa1-e21a3f4acb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getCustomAreaOptionsCovered(event, this, '.formValue', 'propertyType');</value>
      <webElementGuid>991583c0-2ef1-4a50-a4c1-151df7bc25a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyTypeVal&quot;)</value>
      <webElementGuid>a950d0e6-0069-4d47-9e89-a3d655697e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyTypeVal']</value>
      <webElementGuid>91c1740c-63b6-45f1-a2e9-37ad24f27aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pTypSectionDivId']/div[2]/div/span/input</value>
      <webElementGuid>57946978-8d7d-4909-bfb0-c87cee6d7d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[4]/div[2]/div/span/input</value>
      <webElementGuid>5d6f42b4-627a-4c8a-a09c-8e253480b5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'propertyTypeVal' and @name = 'propertyTypeVal']</value>
      <webElementGuid>75119dd3-923e-4724-95a9-e4b68e62b0a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
