<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rent Lease_propertyFor</name>
   <tag></tag>
   <elementGuidId>c2a991e8-7819-4d05-a8f2-9da813620c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyForP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propertyForP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ede06c63-19be-4a1a-a494-f8f0ce60e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyForP</value>
      <webElementGuid>ff7012b1-424f-4df7-aafd-904a2cf67353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyFor</value>
      <webElementGuid>0cba5334-1ae0-486c-9a1e-770cef547d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setflatmat(),customRadioButtonNew(this, 'propertyFor'), showHideDropDown(); firestep2ga('P');</value>
      <webElementGuid>a6e624f3-651c-4ef7-8f28-8baaf2d33b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0519d069-97fe-44f9-9ff1-25958483b2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>34b5ab4b-8cae-43ee-acbd-18349a9e7ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForP&quot;)</value>
      <webElementGuid>15f1680c-5e06-4694-b610-24832b30901d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyForP']</value>
      <webElementGuid>0dc47615-8e81-475c-b7ba-adf35a02ef7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postProperty']/div[9]/div/div[2]/div[2]/div/ul/li[3]/span/input</value>
      <webElementGuid>d8ca81cb-8d58-480c-b486-5bf4ba4d4264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/input</value>
      <webElementGuid>b9345e47-bc01-4a58-b76c-5b5b9d67c757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyForP' and @name = 'propertyFor' and @type = 'radio']</value>
      <webElementGuid>7f4dcf9c-e1ef-4b9f-ac9e-636ad50cb085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
