<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pick your perfect piece of plot</name>
   <tag></tag>
   <elementGuidId>847160d3-f075-4349-99f4-e14e91856386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home_page_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home_page_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>239af9c5-c113-491b-90df-56098a58646b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__heading</value>
      <webElementGuid>b164b71e-f6d4-465e-b435-8f5c0df65bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_page_msg</value>
      <webElementGuid>a4a762ec-fce2-4cb1-a19f-2d892ee748a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Pick your perfect piece of plot
</value>
      <webElementGuid>3e01a6b4-abcf-465c-a08d-b1e2cd5d5410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_page_msg&quot;)</value>
      <webElementGuid>372d6566-b09b-45a3-9de2-bc9893dc914a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home_page_msg']</value>
      <webElementGuid>afd775f7-f5bf-4a75-ae11-2e28d5ddf32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='plotIndex']/section/div/div/div</value>
      <webElementGuid>2f096741-c015-4f2e-abab-65aa6f3019b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay your Rent'])[1]/following::div[3]</value>
      <webElementGuid>cb40a311-91ca-480e-9854-f948e21a1006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Enquiry'])[2]/following::div[4]</value>
      <webElementGuid>31026043-e94e-4128-b823-c4edbc68a28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[2]/preceding::div[1]</value>
      <webElementGuid>2bb64eaa-50d3-471e-a5e8-08e7ef1afc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pick your perfect piece of']/parent::*</value>
      <webElementGuid>6dfccb0f-4a8f-4714-9318-c9e96037267e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/section/div/div/div</value>
      <webElementGuid>3308f33c-f0a5-4c5c-b5bf-8ab7a44ce2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home_page_msg' and (text() = '
Pick your perfect piece of plot
' or . = '
Pick your perfect piece of plot
')]</value>
      <webElementGuid>5d535a26-d849-4c4a-933b-9cf768c6a4b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
