<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Commercial</name>
   <tag></tag>
   <elementGuidId>7dcd7d79-c119-4f52-83f3-0000b70c5bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabCOMM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabCOMM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b423404-547e-4899-874e-8be1fcb7e000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-search__tab__item overclass</value>
      <webElementGuid>fdcd5fcd-755f-4f9d-a0d7-c8371b58846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabCOMM</value>
      <webElementGuid>bcd67e09-8650-4a1a-be66-5a88ce68ece3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fireChangeCategoryGTM(event,'Commercial');openPgTabUrl(this);</value>
      <webElementGuid>a34280b7-9ced-4454-99ae-cd4e9112a5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>https://www.magicbricks.com/property-for-sale-rent-in-Bangalore/commercial-real-estate-Bangalore</value>
      <webElementGuid>2b53d927-90a4-4c73-bdee-3554caa78d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commercial</value>
      <webElementGuid>4953b921-1a58-45d2-8542-c4232550651e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabCOMM&quot;)</value>
      <webElementGuid>e907c6b9-8151-4c89-86b6-7062ac494682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabCOMM']</value>
      <webElementGuid>b4e74107-3af3-4705-83fa-f625af0f3794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='plotIndex']/section/div/div/div[2]/div[5]</value>
      <webElementGuid>9a0cce7c-413a-45c5-b0cc-14644584767b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plot'])[1]/following::div[1]</value>
      <webElementGuid>8bdc32e3-28b6-4773-83d2-91ccce3165ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[1]/following::div[2]</value>
      <webElementGuid>91eaa836-b787-4877-8ff9-0903f4ebdbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Free Property Ad'])[1]/preceding::div[1]</value>
      <webElementGuid>2f0782a5-bdf0-4015-bc8e-984782d50a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bangalore'])[3]/preceding::div[1]</value>
      <webElementGuid>3b10d36f-d221-46ac-b9c4-36ba8337cbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Commercial']/parent::*</value>
      <webElementGuid>91714676-1354-446f-804b-5067937d5b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
      <webElementGuid>a33e2dbd-911b-4f6d-9a85-8c7d97003b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabCOMM' and (text() = 'Commercial' or . = 'Commercial')]</value>
      <webElementGuid>0bb5af47-abe2-4b8d-8efe-afa3d9126f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
