<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maximum sizeallowed is_upload-pic__dialog_b160e5</name>
   <tag></tag>
   <elementGuidId>096ff202-df4d-4d5c-9dc5-6345724a3871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.upload-pic__dialog__box--close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;mbPhotoupload.closeDialogBox(this,'dialogbox')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28aec299-fd45-4b4a-afab-b8237b22cc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>a752e5d9-7fe6-418e-bb65-4978cb881355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-pic__dialog__box--close</value>
      <webElementGuid>6a71f3c9-3ea0-4916-bf73-90db539667a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mbPhotoupload.closeDialogBox(this,'dialogbox')</value>
      <webElementGuid>201e007a-3b85-43da-94f2-20e9d8c2bc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogbox&quot;)/div[@class=&quot;upload-pic__dialog__box&quot;]/a[@class=&quot;upload-pic__dialog__box--close&quot;]</value>
      <webElementGuid>c7c1e2b7-cc9b-4561-9f4a-d423667bf99b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mbPhotoupload.closeDialogBox(this,'dialogbox')&quot;]</value>
      <webElementGuid>e5fdf4a2-9b0f-4ee3-b331-4d27f056702e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialogbox']/div/a</value>
      <webElementGuid>7eaa114c-aca9-40f0-ad61-cca26100c973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>c66e0612-2142-4e00-9315-fb77d4a33fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a</value>
      <webElementGuid>6525332b-6253-49b1-8830-4913708921c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);']</value>
      <webElementGuid>1223d898-f89f-4fd8-80c0-c7e86f85debe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
