<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Single</name>
   <tag></tag>
   <elementGuidId>f2ab5f31-810b-4640-99bc-b23ea21a8102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mobile-form__checkbox-thumb__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slide_pg-roomtype']/div/div[3]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfb9c511-1b14-4bcd-8ab4-8e561cfe0bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-form__checkbox-thumb__label</value>
      <webElementGuid>6aa711ae-bdcf-4a33-a4bd-69871d2cfa98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single</value>
      <webElementGuid>667f6fe1-d1e8-4dde-86df-b2f59cd8f97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide_pg-roomtype&quot;)/div[@class=&quot;mb-pg__screen__left&quot;]/div[3]/div[1]/div[@class=&quot;mobile-form__checkbox-thumb js-checkbox&quot;]/div[@class=&quot;mobile-form__checkbox-thumb__label&quot;]</value>
      <webElementGuid>5ac9a158-43e3-47ca-8da8-9e88ba0e5689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-roomtype']/div/div[3]/div/div/div[2]</value>
      <webElementGuid>15566628-02fc-4e74-b60c-da2f5ae79721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all the available room categories in your PG'])[1]/following::div[5]</value>
      <webElementGuid>c3156ba5-46b1-4090-aa9f-86e8b7a214ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room Categories in your PG'])[1]/following::div[6]</value>
      <webElementGuid>22ea2b72-c09d-4e3e-9d1c-dbbbf83f80f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double'])[1]/preceding::div[2]</value>
      <webElementGuid>e8628ec9-d9ba-48c7-a8de-5a2bc6c49e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triple'])[1]/preceding::div[5]</value>
      <webElementGuid>12b9a0dc-a267-4b7c-8143-03afcad96095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single']/parent::*</value>
      <webElementGuid>1cd5c9eb-d453-42b1-8a78-4ed6bfab0a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[3]/div/div/div[2]</value>
      <webElementGuid>a4c5b536-4c16-4dee-8b49-c2b514657045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Single' or . = 'Single')]</value>
      <webElementGuid>8cfc7c67-fc45-45c6-a990-9ce66fecf3b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
