<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Move into Test, a professionally manage_f4ef12</name>
   <tag></tag>
   <elementGuidId>87286d47-5307-4622-a5ce-c95ff8378f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgDescSample1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pgDescSample1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae5ab76d-84df-4561-914c-7c6b0e267103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__card__more-content</value>
      <webElementGuid>7643fb57-5e99-46a0-8bf7-e16562940ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgDescSample1</value>
      <webElementGuid>3deb57ce-406c-41cd-a99b-673169dad4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Move into Test, a professionally managed PG home in the Western St, Eluru. Located in a safe neighborhood, this male PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.</value>
      <webElementGuid>144730d9-e67a-4909-82a2-3bca6ad4338d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgDescSample1&quot;)</value>
      <webElementGuid>340d48fb-8225-4dea-b8ff-0737d6ff80a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pgDescSample1']</value>
      <webElementGuid>cfffbb62-1fb1-4379-b292-088df988fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-moredetails']/div/div[5]/div[3]/div[2]</value>
      <webElementGuid>bc7eb9c8-e248-4870-8eac-05e854c4fa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample 1'])[1]/following::div[1]</value>
      <webElementGuid>146db519-13f1-4412-b04f-dd900c0553bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample Description'])[1]/following::div[3]</value>
      <webElementGuid>95797adb-e075-4a63-b04e-89a544164a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit &amp; Use'])[1]/preceding::div[1]</value>
      <webElementGuid>5b3e5e4c-d3f6-4b92-b0b6-a501f19e89cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample 2'])[1]/preceding::div[2]</value>
      <webElementGuid>f97adc79-e215-4e16-80d9-1f742ff61791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Move into Test, a professionally managed PG home in the Western St, Eluru. Located in a safe neighborhood, this male PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.']/parent::*</value>
      <webElementGuid>e2ed94fe-9047-4d74-ad06-f95f1bf9d370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div[2]</value>
      <webElementGuid>de93b0c2-6f13-4961-901d-d08c994f30b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pgDescSample1' and (text() = 'Move into Test, a professionally managed PG home in the Western St, Eluru. Located in a safe neighborhood, this male PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.' or . = 'Move into Test, a professionally managed PG home in the Western St, Eluru. Located in a safe neighborhood, this male PG offers various modern amenities for your comfort. This PG has single occupancy types. This PG is nearby major commercial and educational hubs. Please contact the seller to book this fast selling high in demand PG stay.')]</value>
      <webElementGuid>6b766c47-2db0-4d9d-8a94-9d1366505d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
