<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Field Agent will be visiting you so_c9017e</name>
   <tag></tag>
   <elementGuidId>aecbfd19-bddd-4b94-ad31-5a5986aade09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6df1b72-225e-4b83-b43b-5f5271b39e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-close</value>
      <webElementGuid>f1e905af-c023-404a-ab94-b78e62447fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closePopup('pgpckgPopup')</value>
      <webElementGuid>7ddcc951-81b2-49f6-bb38-0aa51c6bff47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgpckgPopup&quot;)/div[@class=&quot;m-popup__table&quot;]/div[@class=&quot;m-popup__table-cell&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;m-popup__content&quot;]/div[@class=&quot;m-close&quot;]</value>
      <webElementGuid>f2e75755-a55c-4a8a-97e9-70d4ed5454f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;closePopup('pgpckgPopup')&quot;]</value>
      <webElementGuid>16af3c54-7aee-488c-9695-d062ebd09790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgpckgPopup']/div/div/div/div/div</value>
      <webElementGuid>c0c2a607-fe9f-4ed3-82fe-57670e6744c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>256b27d7-a142-40c9-992c-d791786af9a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
