<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_houseNo</name>
   <tag></tag>
   <elementGuidId>7f63a208-b7be-4e4e-8f7c-0203a8d2f525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#houseNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='houseNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90af0807-cac4-4100-85a6-0ab3c51fc62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>12b1f739-3bb1-4a2f-9322-1970aec41cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0ea5bdd-d600-4007-99e8-f323f4eec810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>houseNo</value>
      <webElementGuid>73c7b2e1-b206-4314-8744-b1209241874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>houseNo</value>
      <webElementGuid>01f80bbe-3c5c-4ae1-8f79-c47461b4175b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;houseNo&quot;)</value>
      <webElementGuid>7e9f73a8-66d8-4bff-a4eb-5f39d96190f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='houseNo']</value>
      <webElementGuid>c52daae8-deec-4dd7-868c-baf147bfefba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-address']/div/div[4]/div[3]/input</value>
      <webElementGuid>b51a6860-7b80-4674-bc47-3ef134a734f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>6627bf8d-79d4-4ee0-9c1a-9178cb68b4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'houseNo' and @name = 'houseNo']</value>
      <webElementGuid>654e0610-d769-4836-aa75-5c6b14c13a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
