<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__depositPerBed_16011</name>
   <tag></tag>
   <elementGuidId>aaf072da-d66d-4a7a-a2b1-e184b232b64f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#depositPerBed_16011</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='depositPerBed_16011']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8547363-789f-481c-85bf-0f2b51ffd12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>73498862-619b-4ecc-9875-e796d0c92305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ce84816b-6169-4fe7-aad2-7358a17f0550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>depositPerBed_16011</value>
      <webElementGuid>b474dd32-b45e-4cb7-8a52-73604ffe5aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depositPerBed_16011</value>
      <webElementGuid>d63a9980-3cfc-4e3a-8e35-f9455dd59bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8feaab6b-6ac7-4c95-a545-4d23442d2857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>66b69350-c961-44fe-9b8f-cff7062b60b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;depositPerBed_16011&quot;)</value>
      <webElementGuid>f65dc2de-4621-4ecf-a964-4e3e7a69dcf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='depositPerBed_16011']</value>
      <webElementGuid>42bcd4ef-d481-4c38-8bf9-e270ce73435c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roomDetail_16011']/div[3]/div/div[3]/input</value>
      <webElementGuid>04c15db9-911d-4181-8cd6-cbef40205ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/input</value>
      <webElementGuid>d65294db-89ba-4eec-b286-882b3711da83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'depositPerBed_16011' and @id = 'depositPerBed_16011']</value>
      <webElementGuid>4017fcb9-0773-48ca-b0f4-0fbc166947e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
