<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pgzipcode</name>
   <tag></tag>
   <elementGuidId>4b02b08c-6860-41df-a509-fe8f0d12306e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgzipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pgzipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89e842d0-6ba5-4f18-b0f7-6c4c4d7e80d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>bed46276-f6f9-4deb-96cf-8a3c0b500da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1bbf346a-cb31-424b-91d1-5f3c890180cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgzipcode</value>
      <webElementGuid>3f86e46a-edc1-4870-9509-9a32baac81dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgzipcode</value>
      <webElementGuid>f3ad8697-e8db-4cf7-b5ff-b1d9bb369bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a3de75e2-f86e-4721-b153-bcb0178b28cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>5ca8c081-6a29-466a-b99c-bfc13c584bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgzipcode&quot;)</value>
      <webElementGuid>45be26a6-22ee-41e4-b932-5b3649625075</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pgzipcode']</value>
      <webElementGuid>4aac6136-a4f6-4db9-9878-5b85e3ff3a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-address']/div/div[4]/div[4]/input</value>
      <webElementGuid>4b8cd668-4dcd-4aa3-b6d4-785d448409e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>34826cc9-36eb-4ee7-ab7f-8d1673ab6248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'pgzipcode' and @name = 'pgzipcode']</value>
      <webElementGuid>91831974-da7e-4431-8c8b-f6265dc40dd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
