<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The name will be visible to the guest_f40f3a</name>
   <tag></tag>
   <elementGuidId>e607ad3a-2827-4043-b688-a67f3d24e5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pgName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e56bd461-d09b-4cf2-9d0f-d225c95cb816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>50b3f1e2-f518-490b-bb12-23fedda5e21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c2e205f-eb33-47be-bfec-a0f83d5a8097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgName</value>
      <webElementGuid>a52b4f9d-a814-41a6-946e-df4b90a2bffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgName</value>
      <webElementGuid>447cda14-178b-424e-8ed2-bd8d05f49b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgName&quot;)</value>
      <webElementGuid>b824b235-c834-4b05-9d45-90422d55a097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pgName']</value>
      <webElementGuid>bee4de67-2932-4050-877b-126004c1fd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-name']/div/div[3]/div/input</value>
      <webElementGuid>5226df51-2fb3-477d-afcd-974990592577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3e25e940-d444-4b95-82a5-20c2ecff4fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pgName' and @name = 'pgName']</value>
      <webElementGuid>d99b35d1-0195-4d85-99be-891664dd9a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
