<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Single Room_noOfRoom_16011</name>
   <tag></tag>
   <elementGuidId>b791cb92-5729-4cc3-8d6a-dde2b2c722a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noOfRoom_16011</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noOfRoom_16011']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62559cef-a199-4dc8-a34c-54ee4b347b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>cbc8d4a5-63a5-4b4e-979c-13db4f9a2ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e50efa3d-56e4-4333-83e6-acddf02c0263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noOfRoom_16011</value>
      <webElementGuid>74499b9b-df4e-4e35-8bd1-2be9113eb14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noOfRoom_16011</value>
      <webElementGuid>a952cdf7-ebe7-4b31-ab88-2fb80bb2f763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>77bf6ccd-a5fe-428a-91ec-4d68520cfece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>5c268b46-8b99-4450-940a-9f816ada6a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noOfRoom_16011&quot;)</value>
      <webElementGuid>bd0a6e69-9932-43ff-84d7-2bc26ca0a773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noOfRoom_16011']</value>
      <webElementGuid>246c6376-f675-45e5-b83c-36306d937a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roomDetail_16011']/div[3]/div/div/input</value>
      <webElementGuid>5376f274-8cdb-44a7-acce-be4dfd8bc0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>74343655-a2f1-42e2-8fca-78384816f90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'noOfRoom_16011' and @id = 'noOfRoom_16011']</value>
      <webElementGuid>b8e62591-2d39-402d-a089-c1c9c9f058c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
