<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pglandmark</name>
   <tag></tag>
   <elementGuidId>093e12b7-4ed9-4fdc-8173-8614abafd599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pglandmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pglandmark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8adbe59-43fd-4ccb-a3e5-552a678d2d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>5239c81b-b302-4de3-9416-bd2b93886708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6dc6e696-d914-4c19-b868-a07a227d7ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pglandmark</value>
      <webElementGuid>38493bd5-63eb-472d-9cb1-f1da7453f093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pglandmark</value>
      <webElementGuid>a3047888-d9b9-44c4-ba2e-7db9ef3f583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pglandmark&quot;)</value>
      <webElementGuid>380c0b28-7c41-4e4d-89d3-29c1e6ae2b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pglandmark']</value>
      <webElementGuid>9fd33c76-7ad6-43b7-93be-7054972eb650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-address']/div/div[4]/div[5]/input</value>
      <webElementGuid>c94d8e8b-aaac-46c2-8941-76fbcebdb5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>585bd48b-40c7-44f7-91f4-9d7637884750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pglandmark' and @name = 'pglandmark']</value>
      <webElementGuid>554bac61-3713-4a4d-afe8-a3a410bef758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
