<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rentPerBed_16011</name>
   <tag></tag>
   <elementGuidId>4c7c4b1f-1812-483e-b531-2022085ef655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rentPerBed_16011</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rentPerBed_16011']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c44d5e8f-b610-451a-9842-016ecc6a628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input</value>
      <webElementGuid>842cfa22-7c2e-464a-a50d-d292f35cc8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a514a4f8-74a1-4361-b422-d72997e36642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rentPerBed_16011</value>
      <webElementGuid>8b318f64-04df-4e18-a5db-2175e0523f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rentPerBed_16011</value>
      <webElementGuid>36a8bf91-c324-4e9f-b382-7a1cb4731f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>45736509-a3b2-436f-b11e-e8a3d10391cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(mbPg.validate.numbersOnly(this, event, 'M'));</value>
      <webElementGuid>467027ff-461c-44e2-9fae-12352bb0413c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rentPerBed_16011&quot;)</value>
      <webElementGuid>35a8db66-c123-468c-9de5-29e33636fe9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rentPerBed_16011']</value>
      <webElementGuid>4b41d047-f3b1-4b7e-b7ea-265b3293fce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='roomDetail_16011']/div[3]/div/div[2]/input</value>
      <webElementGuid>cae9019e-bdaf-455f-8b08-31efd2624ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>1ecfd5d2-3ed8-40bc-99fe-6c44a968a798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'rentPerBed_16011' and @id = 'rentPerBed_16011']</value>
      <webElementGuid>e0859148-05dd-4cd4-abda-b02b44503c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
