<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make sure you enter the correct addre_b9e526</name>
   <tag></tag>
   <elementGuidId>7fec671b-17fe-4cc8-b3de-a404f01569fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedLocality</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedLocality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d952e333-7e23-40cd-bca2-0250ed40f6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-pg__slide__location__input js-autosuggest</value>
      <webElementGuid>9fd4d8b5-cf3c-4eee-a86a-2a9026f80c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>feef34b5-da43-495e-8227-747e76881590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Locality</value>
      <webElementGuid>4dd19898-e9b0-4f88-8752-9bf7dad2a635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>50a0238b-74e7-4114-9753-b5dc982dd726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedLocality</value>
      <webElementGuid>00814a76-120e-4d21-9fa4-ecdbd1495657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLocality&quot;)</value>
      <webElementGuid>87343c22-53df-4b94-9ae3-40a004711259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedLocality']</value>
      <webElementGuid>e758ebb3-4a45-43c4-b9da-52794cee4a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-location']/div/div[3]/input</value>
      <webElementGuid>728e0af5-2c19-4c2f-b722-593565a7b318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0e13a892-7b64-4b24-b053-99c180ad6513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Locality' and @id = 'selectedLocality' and @name = 'selectedLocality']</value>
      <webElementGuid>0bd30e8f-34be-402b-9f80-0d1249724880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
