<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Add PhotoBuilding ViewRequired Cover pho_8053b1</name>
   <tag></tag>
   <elementGuidId>ac476261-a162-49f5-a770-9c00e1603619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#overview_37601</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='overviewsection_37601']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3ed44cc5-51dd-44c1-a6e2-176ede5017c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-pic__category__list--item</value>
      <webElementGuid>8fca4055-8f83-4433-ab7a-5dfcfc1257e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overview_37601</value>
      <webElementGuid>457ea01e-0cb7-43ae-acd9-6f732fbd17c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add PhotoBuilding ViewRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.</value>
      <webElementGuid>ee0268d0-7ba7-4d61-b574-5b8b362ae89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview_37601&quot;)</value>
      <webElementGuid>40e7fc19-8af5-4a66-80dd-1f652b113029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='overview_37601']</value>
      <webElementGuid>b6aa8885-2bc9-4b0b-a63f-0ba92db67f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='overviewId']/li[2]</value>
      <webElementGuid>883f66ba-e9b1-47e7-8abf-0de16f233999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover photo'])[1]/following::li[1]</value>
      <webElementGuid>2adfb49f-041f-41ea-839b-70f500c24ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[31]/following::li[1]</value>
      <webElementGuid>c7ee6d2d-acea-418b-ad98-df7d0aa46087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li[2]</value>
      <webElementGuid>130e0df0-212d-4750-9cd1-ecc3d3abef2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'overview_37601' and (text() = '+Add PhotoBuilding ViewRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.' or . = '+Add PhotoBuilding ViewRequired *Cover photoPlease upload atleast 1 photoCover photo is the first image that users see when they view your Property listing.')]</value>
      <webElementGuid>aac49d79-58bf-4bc8-a643-a3647046348a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
