<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Western St, Eluru</name>
   <tag></tag>
   <elementGuidId>c006adf6-9946-404e-bd58-39b640850db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.js-dropdown-element</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='locality_options']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8d4131f7-c34a-49fe-b8e2-2b0ffcc87534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-dropdown-element</value>
      <webElementGuid>dbec4f2c-8e3e-4b7d-aef2-061e401b13e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-city</name>
      <type>Main</type>
      <value>2046</value>
      <webElementGuid>6e2d5007-de86-451d-893d-e6b364a7fadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>501</value>
      <webElementGuid>05452213-989c-4ad6-828e-a93bc47b6465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locality</name>
      <type>Main</type>
      <value>Western St, Eluru</value>
      <webElementGuid>6c1e95f2-a47d-4dc1-b1cd-01f5ac239d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-latitude</name>
      <type>Main</type>
      <value>16.705334</value>
      <webElementGuid>5e9d2c7a-18ee-4db4-a076-0e2cc1df6ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-longitude</name>
      <type>Main</type>
      <value>81.10009</value>
      <webElementGuid>464cb348-414f-47c3-b93b-a3251bbfa578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lmtrfnum</name>
      <type>Main</type>
      <value>133039</value>
      <webElementGuid>e3b835ec-9530-4b60-824b-5aed68bbda2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Western St, Eluru
							</value>
      <webElementGuid>4b8ad89d-9131-40d7-9b70-34d90c6e8950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locality_options&quot;)/li[@class=&quot;js-dropdown-element&quot;]</value>
      <webElementGuid>3055bf74-122f-4168-bec0-64427fb501ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='locality_options']/li</value>
      <webElementGuid>d45e418f-7c14-42f5-8cdd-fa8913809cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure you enter the correct address for a smooth verification.'])[1]/following::li[1]</value>
      <webElementGuid>9b4efd27-0ec5-4d2d-8de6-2875548e8639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where is your PG Located?'])[1]/following::li[1]</value>
      <webElementGuid>53a1db9c-74bb-4a14-a121-59a4045189e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ern St, Eluru']/parent::*</value>
      <webElementGuid>90d5d611-3bc7-4f58-a614-41c2ab4a0836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>224ceacd-19ab-465e-ba80-c60e12298cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
								Western St, Eluru
							' or . = '
								Western St, Eluru
							')]</value>
      <webElementGuid>cade2d3f-004b-4f75-a78b-206029920994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
