<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tell us more about your PG_pgdescription</name>
   <tag></tag>
   <elementGuidId>e4a32aac-fc01-4e0c-b926-db5543f17b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pgdescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pgdescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6647f5f7-159b-4e84-8ef6-462c9b26f7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-form__input mb-form__textarea</value>
      <webElementGuid>c2c09b9a-8c2c-4ef7-b211-2ffff250253a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>mbPgUi.autoGrow(this)</value>
      <webElementGuid>3c637449-2981-437b-b939-0b47db3e3c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pgdescription</value>
      <webElementGuid>f9beb498-e33d-4fc0-a314-cac2dffc1e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pgdescription</value>
      <webElementGuid>b1225e48-9ea3-460f-9977-931c0cad53ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgdescription&quot;)</value>
      <webElementGuid>eae8f815-e1e3-475f-8718-160aaa51e1cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pgdescription']</value>
      <webElementGuid>21f032b0-a015-402a-a82f-34f4f23caf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide_pg-moredetails']/div/div[3]/div/textarea</value>
      <webElementGuid>c6a54f2d-626a-4e9c-97c3-79c4817cb8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>067e6998-d274-45d3-91fb-a4ce398e94a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'pgdescription' and @name = 'pgdescription']</value>
      <webElementGuid>a00cb2d7-9ba3-4657-9301-8b7e7183d68a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
