<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>ed82fd30-e301-403e-9c2c-0ae1fccb1942</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn_pg-continue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='redirectPgUrl();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>775142b2-387b-40dc-9418-555079b301e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>c460015f-912a-489a-8f4e-f44995f80c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectPgUrl();</value>
      <webElementGuid>95dab2e2-f9d4-4e56-9bc3-accec93d920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_pg-continue</value>
      <webElementGuid>138c0fde-9928-4c77-ab4f-992e3ab3c1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>01d12401-ccc6-4827-818f-0b2bad83be3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pgSpecificRedirectDiv&quot;)/div[@class=&quot;form_element_group&quot;]/a[@class=&quot;btn_pg-continue&quot;]</value>
      <webElementGuid>1f60435e-2f9a-4549-b07d-75c7c65ec685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='redirectPgUrl();']</value>
      <webElementGuid>1de62d9f-b919-4890-b85c-d026bcc3451b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pgSpecificRedirectDiv']/div[2]/a</value>
      <webElementGuid>446e442b-fd32-4915-8fc1-2f09bfaeb898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Continue')])[5]</value>
      <webElementGuid>7353e49f-02c3-4fb1-a70f-f39b4880aa38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Get started with our new listing form - it', &quot;'&quot;, 's super quick and simple.')])[1]/following::a[1]</value>
      <webElementGuid>baf68e57-92da-4713-bb17-101f103abe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now post your Property in just a few minutes!'])[1]/preceding::a[1]</value>
      <webElementGuid>04b1e6da-a054-4452-badc-c11bd1453b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Get started with our new listing form - it', &quot;'&quot;, 's super quick and simple.')])[2]/preceding::a[1]</value>
      <webElementGuid>c20eb883-52f5-4d20-9d77-31b8b830e2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>3ac76996-30fd-4e93-b1c7-260a4d24cbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>2225ab08-8c05-41d0-b3e9-ce62cb5fbf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>2ce19604-e8c5-4641-bbfd-38759657b0c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
