<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rent Lease_propertyFor</name>
   <tag></tag>
   <elementGuidId>6b5f0e34-5555-4a75-97a0-96c33fafbddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyForP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyForP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b9dc195-1d15-4abd-bd29-fce9f6431bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyForP</value>
      <webElementGuid>9e4766eb-6c7b-4e3e-a6ed-f1590ec7ebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyFor</value>
      <webElementGuid>2ba258ab-390b-4078-bfb0-b1dfe21fc5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setflatmat(),customRadioButtonNew(this, 'propertyFor'), showHideDropDown(); firestep2ga('P');</value>
      <webElementGuid>27cb6dde-3b79-4cdd-a1ce-0c950a58717c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d17ad1c5-fb66-4cb2-a387-1950b013c690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>c510cd43-dfa2-40b1-9d46-f0b32b94aa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForP&quot;)</value>
      <webElementGuid>ae423725-b4d9-4aba-9138-68a7caad564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79756f3c-2c87-47e3-8e96-e07e26cd4af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyForP</value>
      <webElementGuid>faf2f317-e3af-4ca1-aa65-8aa18ec1b97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyFor</value>
      <webElementGuid>62d495e6-c66d-42bb-bf3e-0304bf3facd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setflatmat(),customRadioButtonNew(this, 'propertyFor'), showHideDropDown(); firestep2ga('P');</value>
      <webElementGuid>e3ce83fc-f170-402f-95d7-8dfae8bde563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>59ff4ad6-2eca-47e1-bdce-4f3090a2b93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>8efb9a2e-bfc0-4143-80c6-0fafbb21dc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyForP&quot;)</value>
      <webElementGuid>0721c556-3761-4a49-a8cb-9d834716ee56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyForP']</value>
      <webElementGuid>d0c4f285-46ca-4861-838d-fdfc70ef488f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postProperty']/div[9]/div/div[2]/div[2]/div/ul/li[3]/span/input</value>
      <webElementGuid>def1046e-2c3d-452b-8c2c-105f4b5033ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/input</value>
      <webElementGuid>9ba942a3-bf24-4663-851a-6f0d25d8cbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'propertyForP' and @name = 'propertyFor' and @type = 'radio']</value>
      <webElementGuid>3e6930fa-7f26-430c-80ec-b5b021e5e6c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
